### PR TITLE
[core] Introduced the CSharedResource

### PR DESCRIPTION
**Pull request by maxsharabayko**
NB! The description is outdated, as now issue #2234 is being addressed in this PR.

Introducing the `CSharedResource` class. Not yet used in the code. Potentially the `m_ConnectionLock` can be converted to the `CSharedResource`.

### CODE REVIEW

**Comment by ethouris** [comment]
The "shared resource" type is introduced exactly in order to not lock mutexes guarding the container access in order to run some longer procedure on an object contained in this container.

**Comment by gou4shi1** [comment]
> The "shared resource" type is introduced exactly in order to not lock mutexes guarding the container access in order to run some longer procedure on an object contained in this container.

It looks like `std::shared_ptr`?

**Comment by ethouris** [comment]
No. This is for objects potentially being used by multiple threads at a time and at some point they have to be deleted.

**Comment by gou4shi1** [comment]
> No. This is for objects potentially being used by multiple threads at a time and at some point they have to be deleted.

If all users of the shared_ptr (from different threads) end, the resource will be deleted automatically.

**Comment by gou4shi1** [comment]
> It looks like `std::shared_ptr`?

For example, `m_Sockets` could be `std::map<SOCKETID, std::shared_ptr<CUDTSocket>>`, all other containers only keep `std::weak_ptr<CUDTSocket>`, if some function need a temporary ownership of a socket, it can just use `std::weak_ptr<CUDTSocket>::lock()`, without need to hold `m_GlobControlLock` in the whole function to guard the socket existence.

**Comment by maxsharabayko** [comment]
Closing as outdated and partially covered by PR #2981 (a SharedMutex class).

**Pull request closed without merging**
