### PR TITLE
Build system reinvention, to compile srt to a single library file.

### PR DESCRIPTION
**Pull request by ethouris**
1. CMakeLists.txt is back again one central. The detailed definitions for haicrypt and srtcore dirs are now intermixed and it's no longer possible to keep them separately.
2. The things specific for particular subproject are now contained exclusively in `filelist.maf` file. This is more-less the old solution using `HEADERS.maf` file, just this time sources are also contained there.
3. The reading from MAF file is now done by a macro defined in `haiUtil.cmake` and it's purely coded in cmake language. The `mafread.tcl` file remains only for historical reasons and as an example of the expected logical functionality.
4. The "haicrypt" library has now the VIRTUAL libspec by default, which is a logical term stating that its sources are directly incorporated to the sources of the dependent library, and all flags and linker settings apply to the dependent library directly. This makes that the resulting library file is just one, named `libsrt.so` or `srt.dll` in case of shared libraries.
5. The option `ENABLE_SEPARATE_HAICRYPT` now controls compiling haicrypt as a separate library, in which case it gets the same libspec as srt. If not set (default), the haicrypt's libspec is "virtual", which results in that everything is compiled into one single library, with libspec as defined for SRT. Note that common windows stuff in this case is attached to haicrypt, as it was before. This mode actually is predicted to be used on Linux/ARM only (Haivision requirement), so there's no extra common windows stuff to be attached and controversially exported.

### CODE REVIEW

**Comment by russelltg** [comment]
Probably smart to merge master into this, considering there are conflicts.

**Comment by ethouris** [comment]
I have merged it already twice and looxlike I must create a separate branch.

Git tries to be smarter than me and it has outsmarted me. I'll abandon this and create a new one.

**Comment by ethouris** [comment]
Actually I wanted to withdraw it, but there's no button for that...

**Comment by russelltg** [comment]
Keep in mind you can always force push to a branch using `git push <remote> +<branch>` :)

**Pull request closed without merging**
