### PR TITLE
Renamed legacy UDT_EPOLL_* symbols

### PR DESCRIPTION
**Pull request by ethouris**

### CODE REVIEW

**Comment by maxsharabayko** [comment]
@ethouris Given that they are replaced, do you think we still have to preserve those in udt.h?
```
#define UDT_EPOLL_OPT SRT_EPOLL_OPT
#define UDT_EPOLL_IN SRT_EPOLL_IN
#define UDT_EPOLL_OUT SRT_EPOLL_OUT
#define UDT_EPOLL_ERR SRT_EPOLL_ERR
```

**Comment by ethouris** [comment]
Yes, we need to get rid of legacy symbols only when we are certain no one is using them any longer. The problem is that these symbols are public, so removal of them is not so simple process.

**Comment by maxsharabayko** [comment]
Ok, created a small note in #994. Maybe worth removing the UDT API. To be discussed later.

**Comment by ethouris** [comment]
It would be also nice to provide a real-world C++ API for SRT, but we need lots of refactoring in the base code structure first. There's some usefulness of the complementary C++ API, and it's now merged together with the legacy UDT API, which is still in use in many apps.

**Comment by maxsharabayko** [comment]
@ethouris 
> ... the legacy UDT API, which is still in use in many apps.
Are we aware of any of those uses of SRT via the UDT API?

**Comment by ethouris** [comment]
I doubt about any apps in the open source world. Rather some of the older code among Haivision products. We'd have to get signal from all devel teams using SRT that they no longer use any old UDT-based API, or at least aren't going to upgrade SRT to a newer version.

**Pull request merged**
