### PR TITLE
[core] Removed invalid max socket ID check

### PR DESCRIPTION
**Pull request by ethouris**

### CODE REVIEW

**Review by maxsharabayko — APPROVED** [review]
```c++
static const int32_t MAX_SOCKET_VAL = 1 << 29;    // maximum value for a regular socket
```
The check for Socket ID value was also rejecting some sockets with IDs above 1 << 29. 
`m_iID >= CUDTUnited::MAX_SOCKET_VAL`

The actual valid socket ID range is:
- Single socket ID range: [1; 2^31)
- Group socket ID range: [2^31; 2^32)
- If the destination ID is 0, the packet will be sent to the listening socket or to a socket that is in rendezvous connection phase

**Comment by ethouris** [comment]
This is not subject of this PR.

Checking this ID was wrong because in case when getting a connect request from SRT in previous version in which the socket has a value from the range reserved for Group ID, this socket value should be still treated as valid. It's the value that is used by the current connection as a "peer ID" and it perfectly can have that value. The "agent" should only take care that a value of the socket locally (when created, or newly accepted) is not in the range of groups, but that will never happen in a version with group support.

The maximum socket value is a different story, please continue it in #1816

**Comment by maxsharabayko** [comment]
> The range for single-socket-id and group-id together cover the whole numeric range for a 32-bit integer, with 0 being of course an exception, but also a value allowed in the handshake. Therefore no check is necessary at all - all values are allowed here.

So not the whole range, but only `[1; 2^31)`, meaning that negative values are excluded. 🤔 
Or we don't care about the Socket ID value of the remote peer?

**Comment by ethouris** [comment]
At least an invalid value of the socket isn't harmful for the application stability, and this is exactly what we wanted to prevent with this check. At worst the connection will be broken because one of the facilities will happen to check if the socket ID occasionally isn't -1 - but that behavior in case of a rogue peer is fully expected.

**Pull request merged**
