### PR TITLE
gitignore

### PR DESCRIPTION
**Pull request by funman**

### CODE REVIEW

**Comment by ethouris** [comment]
Bad idea. This enumerates files that are created during the build process, however these may change names in future, as well as need not be created here at all because the build can be created also in a shadow directory, which is highly recommended.

If you have problems with remaining build files that pollute the source directory, and you need something of a kind of `make distclean` from Autotools that does not exist in `cmake`, I'd recommend using `cmake-clean` from [This package](https://gitlab.com/posix-tools/posix-tools).

**Comment by funman** [comment]
If files change in the future we can update the gitignore.

Also in place of distclean I'd use git clean -fxd ;)

I note that external build directory is preferred

**Comment by ethouris** [comment]
Well, for that exactly purpose, I'd use rather `git most -ou | xargs rm -rf` (with git-most script from [This package](https://gitlab.com/git-tools/git-tools) ). At least it gives me a chance to review the existing files before deletion (I can add `| xargs...` later).

(yes, both mentioned packages on Gitlab are my creation, my consciousness bites me a little for making an ad here :) ).

**Comment by funman** [comment]
So is having a gitignore harmful in any way?

**Comment by ethouris** [comment]
Well, I forgot to make a blog entry about that at the time when I lost hours of useless trying to fix a repository, which was caused by the fact that something has accidentally matched the contents of `gitignore` hidden in some dark place. The problem appears especially if there's a temporary collision between private files and in-repo files, which happen to be accidentally embraced by gitignore.

But anyway, I had a very bad experience with this, and if there's a problem that can be solved without adding a gitignore, this solution better be preferred.

**Pull request closed without merging**
