### PR TITLE
Make manifest files sane

### PR DESCRIPTION
**Pull request by russelltg**
This way installed versions work :)

### CODE REVIEW

**Comment by ethouris** [comment]
Oh dear, now I can see what is currently in the sources... :)

It's good to have these in separate lists, just please try to make it a little bit differently:

1. The `Sources.txt` file should use some other format that supports sections. I don't impose the previous idea with `HEADERS.maf` file, it can be anything that supports sections. Alternatively you can keep every section in a separate file, but this seems for me too noisy. Would be nice to have something that cmake can interpret "out of the box" (or in the last resort, provide some parsing macro in haiUtil.cmake).
2. Split the contents of "Sources.txt" into sections: SOURCES, PRIVATE HEADERS, PROTECTED HEADERS, PUBLIC HEADERS.

SOURCES are all *.cpp files. PUBLIC HEADERS are those that are predicted to be #included in the user's code, PROTECTED HEADERS are those that are intermediately used by the public headers, and PRIVATE HEADERS are all other *.h files.

This way you don't have to define which headers are public in the cmake variables, but just directly in this listing file. The public and protected headers should be then extracted for installation.

Actually it wasn't my exact intention to use the logical meaning of "srtcore" directory as a base for whole srt library (that's why the build definitions were at the toplevel, and this directory was only to keep source files of particular category), but well, that's actually a good idea. But if so, then probably the parts of the toplevel CMakeLists.txt file that concern both haisrt and haicrypt parts, as well as applications, should be as short as possible, and rather moved to their counterparts in the directories.

**Comment by russelltg** [comment]
This all sounds like a great idea. 

How about a `Manifest.cmake` file that sets the variables and is then included by the `CMakeLists.txt`?

**Comment by ethouris** [comment]
Could be, but somehow I don't like this idea. The logical order of things sounds like that there's kinda database in the file and it's being queried for data. A file that already sets the variable is something different - it will make the cmake look like "taking the variables from the air". This should rather look like that the variables are being set in the file that uses them, and the actual data extracted from the containing file are specified in a form of query (request with parameters - can be also a cmake macro). The `include(Manifest.cmake)` instruction hides the actual names of the variables that are being set here.

**Comment by russelltg** [comment]
It could live in a macro looking like:
```cmake
extract_sources(Manifest.cmake 
    PUBLIC_HEADERS <variable name> 
    PROTECTED_HEADERS  <variable name>
    PRIVATE_HEADERS <variable name>
    SOURCES <variable name>
)
```

**Comment by ethouris** [comment]
Yes, that definitely does. Just how would this be defined in the Manifest file?

**Comment by russelltg** [comment]
Possibly something like
```cmake
define_component_sources(
COMPONENT srt
PUBLIC_HEADERS
    public_header.h
SOURCES
    src.cpp
)
```

and `define_component_sources` could look like

```cmake
macro(define_component_sources)

    cmake_parse_arguments(define_component_sources "" "COMPONENT" "PUBLIC_HEADERS PROTECTED_HEADERS PRIVATE_HEADERS SOURCES" ${ARGN} )

    set(${define_component_sources_COMPONENT}_PUBLIC_HEADERS "${define_component_sources_PUBLIC_HEADERS}")
    ....

endif()
```


Then the `extract_sources` would look like
```cmake
extract_sources(
    COMPONENT srt 
    PUBLIC_HEADERS <variable name> 
    PROTECTED_HEADERS  <variable name>
    PRIVATE_HEADERS <variable name>
    SOURCES <variable name>
)
```
It would assume there's a `Mainifest.cmake` file in the current directory

**Comment by ethouris** [comment]
It gets a little bit complicated. How about having the exact text passed here to `define_component_sources` contained in the manifest file? Whatever macro then you'd like to use to extract it, it will be contained exclusively in CMakeLists.txt file. Then you'd use `file(READ ...)` to a variable, which's value will be next passed to `define_component_sources`, or just parsed on the fly like this:

```
extract_sources(Manifest.txt
  PUBLIC_HEADERS SRT_PUBLIC_HEADERS
  PROTECTED_HEADERS SRT_PROTECTED_HEADERS
  SOURCES SRT_SOURCES
)
```
And the `extract_sources` will then put the contents of `Manifest.txt` into the parser. This will keep the manifest file just a data holder, independent on any scripting things in cmake.

Then `Manifest.txt` will just look like:
```
COMPONENT srt
PUBLIC_HEADERS
    public_header.h
SOURCES
    src.cpp
```

**Comment by russelltg** [comment]
That sounds like a good plan. I'll draft it up.

I suggest we keep this PR so the conversation stays, if that's alright. I'll rename it.

**Comment by russelltg** [comment]
That should work nicely :)

**Comment by russelltg** [comment]
I'm going to close this because #62 fixes this.

**Pull request closed without merging**
