### PR TITLE
Changing defaults tsbpdmode=true latency=120

### PR DESCRIPTION
**Pull request by ethouris**
Also some cosmetics, and removed obsolete TSBPDMAXLAG also from socketoptions.

### CODE REVIEW

**Comment by rndi** [comment]
Thank you!

**Comment by alexpokotilo** [comment]
I have simple test that start failing after this feature integrated.

```
void clientSocketSyncClientTarget() {
    m_client_sock = srt_socket(AF_INET, SOCK_DGRAM, 0);
    ASSERT_NE(m_client_sock, SRT_ERROR);
    sockaddr_in sa;
    memset(&sa, 0, sizeof sa);
    sa.sin_family = AF_INET;
    sa.sin_port = htons(9999);

    ASSERT_EQ(inet_pton(AF_INET, "127.0.0.1", &sa.sin_addr), 1);

    sockaddr* psa = (sockaddr*)&sa;

    ASSERT_NE(srt_connect(m_client_sock, psa, sizeof sa), SRT_ERROR);


    char pattern[4] = {1, 2, 3, 4};

    for(int i = 0; i < 1000; ++i) {
        char buffer[1316];
        ASSERT_EQ(srt_recvmsg(m_client_sock, buffer, sizeof buffer), // in case if passphrase set first recv return -1
                  1316);

        EXPECT_TRUE(ArraysEqual(pattern, buffer, sizeof pattern));
    }

    LibSrt::srt_close(m_client_sock);
}

void serverSocketSyncServerSource() {
    int yes = 1;

    SRTSOCKET m_bindsock = srt_socket(AF_INET, SOCK_DGRAM, 0);
    ASSERT_NE(m_bindsock, SRT_ERROR);

    ASSERT_NE(srt_setsockflag(m_bindsock, SRTO_SENDER, &yes, sizeof yes), SRT_ERROR);

    sockaddr_in sa;
    memset(&sa, 0, sizeof sa);
    sa.sin_family = AF_INET;
    sa.sin_port = htons(9999);
    sa.sin_addr.s_addr = INADDR_ANY;
    sockaddr* psa = (sockaddr*)&sa;

    ASSERT_NE(srt_bind(m_bindsock, psa, sizeof sa), SRT_ERROR);
    ASSERT_NE(srt_listen(m_bindsock, SOMAXCONN), SRT_ERROR);

    sockaddr_in scl;
    int sclen = sizeof scl;

    SRTSOCKET m_sock = srt_accept(m_bindsock, (sockaddr*)&scl, &sclen);
    ASSERT_NE(m_sock, SRT_INVALID_SOCK);

    char buffer[1316] = {1, 2, 3, 4};

    for(int i = 0; i < 1000; ++i) {
        ASSERT_NE(srt_sendmsg(m_sock, buffer, sizeof buffer,
                                      -1, // infinit ttl
                                      true // in order must be set to true
                                      ),
                  SRT_ERROR);
    }


    srt_close(m_sock);
    srt_close(m_bindsock);
}

TEST(SRT, SimpleSyncServerSource) {
    ASSERT_TRUE(IsSrtAvailable());
    ASSERT_EQ(srt_startup(), 0);

    boost::thread server(&serverSocketSyncServerSource);
    boost::thread client(&clientSocketSyncClientTarget);

    server.join();
    client.join();

    srt_cleanup();
}

```
it starts failing on srt_recvmsg after about 780 successful receive.
I disabled TSBPDMODE for both server and client and after that srt_recvmsg failed after about 970  successful receive.
I understand that with TSBPDMODE enabled it should fails in this test but why it fails if I disabled TSBPDMODE ?

**Comment by ethouris** [comment]
There's really nothing changed beside that TSBPDMODE is now on by default, so turning it off should simply make up for the old behavior. I have also changed the default latency from 20 to 120 - with TSBPDMODE turned off this shouldn't make a difference.

Did you really use this:

`bool no = false; srt_setsockflag(m_bindsock, SRTO_TSBPDMODE, &no, sizeof no);`

on both sides?

Also, if you are going to transmit files, remember that for that mode you must also somehow limit the transmission bandwidth, otherwise you risk losing packets. By default the bandwidth isn't limited (30Mbps is set as limit), which is good enough for media transmission, as media are never transmitted with such a speed as when you read from file from the local filesystem. You can try to experiment with setting SRTO_MAXBW to 0 and tweaking SRTO_INPUTBW and SRTO_OHEADBW.

**Comment by alexpokotilo** [comment]
Hi,
yes I'm sure I set off SRTO_TSBPDMODE on both sides.
```
int no = 0;
srt_setsockflag(m_bindsock, SRTO_TSBPDMODE, &no, sizeof no);

```

but I think it's the same as if I use **bool no**
You can easily reproduce this case locally. I've checked simple diff of this commit and cannot say why this happens. If I switch to previous version test above passed. If new version used and even though I set SRTO_TSBPDMODE off test failed.
I just want to emphasize that this simple change can break something else so we need to make sure it's safe. It's strange that it works before and stop working. Please let me know if you need further help to reproduce this case and check

**Comment by ethouris** [comment]
For the sake of C language, the boolean options can accept values from both bool and int types (the size is checked to select correct type). So yes, this can be `bool` and `int`.

Should this somehow solace you (because I wouldn't call it help) is that I'm doing final testing for the integrated handshake feature and I too have problems with transmitting a file. Still trying to determine the root cause. I'm sure this must be some problem that was in the SRT since the beginning, just probably it's only visible under certain conditions.

Let me add this to the queue then.

**Comment by alexpokotilo** [comment]
Thanks a lot ! I'm not planning to bother you further just want to point to the problem and simple case to reproduce it. And it's great that this will probably gone with new release

**Comment by ethouris** [comment]
If you can have some reproduction procedure for any kind of problem, it's always welcome. Once you have it, file a new issue so that we can take a closer look.

**Pull request merged**
