### PR TITLE
Add supporting nettle/gnutls

### PR DESCRIPTION
**Pull request by justinjoy**
OpenSSL has non-GPL compatibility problem.
For GPLed software, Nettle and GnuTLS can provide
alternative.

Signed-off-by: Justin Kim <justin.kim@collabora.com>

### CODE REVIEW

**Comment by justinjoy** [comment]
I check whether it works. However, I am not sure this patch still meets the author's intention.
Please, advise me.

**Comment by justinjoy** [comment]
CI build failure report seems not to be related to this patch.

https://travis-ci.org/Haivision/srt/jobs/288529036#L1630
```
The command "brew install openssl" failed and exited with 1 during .
```

**Comment by rndi** [comment]
Hello Justin,

Could you try picking this commit into your branch:

https://github.com/Haivision/srt/commit/f9ccaa00049739da28d03c8e40314992e86adde6

It should help with Travis CI build isse.

Thanks!

**Comment by jeandube** [comment]
@justinjoy You said that you check wether it works. What test did you performed. I saw in yout changed that you updated the haicrypt unit tests but the change in csrtcc.cpp makes me doubt a NETTLE-based SRT app compiled with this patch can interoperate with a peer compiled with openssl.
You basically hijacked the opensslAES hcrypt_Cipher This is a good start but hcrypt_Cipher was defined for this reason: use other cipher libs. You should have made a NETTLE-only hcrypt_Cipher (hc_nettle_aes.c) without opensll calls or #ifdef NETTLE. This cipher hook might not be complete since it was never used for anything else than openssl. It does not address higher level funcitionalities such as AES-KEY-WRAP, PBKDF2, or even HMAC but your work is an opportunity to fix it.

**Comment by justinjoy** [comment]
@rndi I sent pr again with cherry-picking f9ccaa0 to check buildable. Thanks.

@jeandube please check my comment.
> What test did you perform?

I just checked stream converting (udp -> srt -> playing with srt module in VLC) for nettle based srt.
I missed the compatibility with openssl based implementation.

>  I saw in your changes that you updated the haicrypt unit tests but the change in csrtcc.cpp makes me doubt a NETTLE-based SRT app compiled with this patch can interoperate with a peer compiled with openssl.

I don't know much about cryptographic, but I modified `csrtcc.cpp` because a defined macro seems not to handle `else` case properly.
According to `CMakeList.txt`, `HAICRYPT_USE_OPENSSL_EVP` can be selectable so I disabled this definition and fix the `else` case in `csrtcc.cpp` 

> You basically hijacked the opensslAES hcrypt_Cipher. This is a good start but hcrypt_Cipher was defined for this reason: use other cipher libs.

Yes, but it sounds like refactoring of haicrypt. For the first time, I thought your recommendation approach. However, I concluded that doing so is much more than porting job because even common header such as 'hcrypt.h' has lots of OpenSSL things.

**Comment by jeandube** [comment]
@justinjoy I cannot see how you can decrypt a received encrypted SRT stream since you don't set the cipher in the crypto context. I assume that the udt->srt flip is performed with stransmit as the SRT source for the nettle-based SRT VLC receiver. If this is an openssl-based SRT stransmit the passphrase="something" option shall enable encryption (otherwise this is plain mpeg-ts). This is what I meant by openssl interop. You need a known good implementation to test yours. If you use a nettle-based stransmit than a packet trace (wireshark) can be used to check that stream is encrypted.

**Comment by justinjoy** [comment]
I understand what you point out. My patch is just starting point to link with nettle for plain-stream. If passphrase is given, it will not work because of missing chiper. I didn't check when `passphrase` option is given. I think porting nettle is not sufficient. To make it work correctly,  I should use gnutls APIs.

**Comment by justinjoy** [comment]
I will re-submit different PR by using slightly different approach to support multiple SSLs.

**Pull request closed without merging**
