### PR TITLE
Master patch mcast stransmit win

### PR DESCRIPTION
**Pull request by lewk2**
Attached is the specific relevant change required for correct binding to multicast input when working on Windows - hand-ported just multicast parts from changes made by ethouris in his branch which tracks 'dev'.

### CODE REVIEW

**Comment by ethouris** [comment]
Nice if you fix the indents. Note that they all use spaces (vim: expandtab).

**Comment by lewk2** [comment]
That is done (tabs came from making the change inside online Git editor... )

**Comment by ethouris** [comment]
One more thing to fix - I forgot to set sin_family = AF_INET when using INADDR_ANY. Strange thing that only Windows reported a problem there.

**Comment by rndi** [comment]
@lewk2 the idents still don't look right. Let me know if you have trouble with this and I will try to do the change on my side and update your branch.

Also there have been more changes to #104 that are relevant to the issue. Do you think you can look into adding those to this pull request and maybe testing them on your setup?

Thanks!

**Comment by ethouris** [comment]
Yes, please. The REUSEADDR option should fix the problem with locked socket, so please apply also this one and check if everything's ok.

**Comment by lewk2** [comment]
Just waiting for final CI tests, but I compiled locally and was able to use 1 tool to generate a multicast source on the same station that then transmits using stransmit.

If CI completes (and 2 / 4 are OK already) then it should be good to merge now.

**Comment by rndi** [comment]
Thank you @lewk2 !

**Pull request merged**
