### PR TITLE
Removed condition for getting timespan

### LINKED ISSUE #900: Perf stats instantenious timespan of the receiver's buffer
`CRcvBuffer::getRcvDataSize(…)` reports the timespan of acknowledged packets in the receiver's buffer only if TSBPD is enabled. Although the value might be useful in both cases.

Note that the same function is used for TSBPD thread to trigger packet drop.

### PR DESCRIPTION
**Pull request by ethouris**
Fixes #900

### CODE REVIEW

**Comment by ethouris** [comment]
> 1. If TSBPD is disabled, packet timestamp is a sending time,

Not if TSBPD is disabled, but when TSBPD is disabled **and** user timestamp is not specified. In simplification, we can state it is always the case (if a user doesn't supply the monotonic values here, it's his problem).

> therefore timestamp of the very first packet in the receiver's buffer might be not the earliest one.

It is always the earliest one, at least when the monotonic clock is used as a source for the timestamps. And, looxlike, it is.

```
            setPacketTS(w_packet, steady_clock::now());
```

Besides, we are talking here about a function that is called from `updRcvAvgDataSize`, which is also called exclusively once in `CUDT::tsbpd()`:

```
#ifdef SRT_ENABLE_RCVBUFSZ_MAVG
        self->m_pRcvBuffer->updRcvAvgDataSize(steady_clock::now());
#endif
```

The other call is done for statistics probing:
```
#ifdef SRT_ENABLE_RCVBUFSZ_MAVG
            if (instantaneous) // no need for historical API for Rcv side
            {
                perf->pktRcvBuf = m_pRcvBuffer->getRcvDataSize(perf->byteRcvBuf, perf->msRcvBuf);
            }
            else
            {
                perf->pktRcvBuf = m_pRcvBuffer->getRcvAvgDataSize(perf->byteRcvBuf, perf->msRcvBuf);
            }
#else
            perf->pktRcvBuf = m_pRcvBuffer->getRcvDataSize(perf->byteRcvBuf, perf->msRcvBuf);
#endif
```

And that's about all that this change has influence in the current code.

> 2. Will the function `getPktTsbPdTime()` work correctly if TSBPD is disabled?

If TSBPD is disabled, it is used only to display some logs and possibly in belated packet stats (which is insignificant for other than live modes).

> It might be that #900 was a bad idea. Removing "approved" status: requires pondering.

Depends on what you wanted to achieve. This change in the present code is insignificant, but it can open some interesting opportunities in the future.

**Comment by maxsharabayko** [comment]
> t is always the earliest one, at least when the monotonic clock is used as a source for the timestamps.

In case of peer TSBPD is disabled, a timestamp of a retransmitted packet corresponds to retransmission time, not the initial sending time of the original packet.
It means that the first packet in the receiver's buffer (if it was retransmitted) can have a timestamp higher than the latest sequential packet in the buffer.

`CUDT::packData(..)`:
```c++
if (m_bPeerTsbPd)
{
    if (origintime >= m_stats.tsStartTime)
    {
        setPacketTS(w_packet, origintime);
    }
    else
    {
        setPacketTS(w_packet, steady_clock::now());
    }
}
else
{
    setPacketTS(w_packet, steady_clock::now());
}
```

**Comment by ethouris** [comment]
Still, the TSBPD time isn't used for anything for now if TSBPD is disabled - fortunately. It means, however, that we might need to consider stable times also out of TSBPD mode, and preserve the original scheduling time in the timestamp field.

This is a change towards UDT rules, however OTOH the timestamp field in UDT is informational only, and not used for anything. We might also do it a little bit differently in file mode - like, e.g. set the timestamp at the packing time, but preserve the original packing time for retransmitted packets (so that span time can be counted reliably and these timestamps can be also used to compare sending and reception speed in file mode). AFAIR we don't have anything strictly defined for that case as of now for SRT protocol.

**Comment by ethouris** [comment]
Closing because the fix refers to the old (original) version of the receiver buffer that has been already replaced.

**Pull request closed without merging**
