### PR TITLE
Changed priority rule to higher preferred. Set uint16_t as weight type.

### LINKED ISSUE #1545: Change the interpretation of the weight for the main/backup mode
The `weight` value provides so a socket in a group must conform to the following conditions:

1. The `weight` is a 16-bit unsigned integer value.
2. The default value must be 0.
3. The higher weight means a higher priority.
4. Two links having the same weight have the same priority.

### PR DESCRIPTION
**Pull request by ethouris**
Fixes #1545

### CODE REVIEW

**Comment by maxsharabayko** [comment]
What about changes in SRT API and Group Membership Extension?
Documentation has to be updated to at least state the higher weight corresponds to a higher priority.

**Comment by maxsharabayko** [comment]
Handshake wrapping should work without changes, right?
```c++
| SrtHSRequest::HS_GROUP_WEIGHT::wrap(m_parent->m_IncludedIter->weight);
```

Do we need to **additionally** limit the range of possible values of the weight, e.g. to int16_max 32767?
At least from the protocol point of view it leaves us an opportunity to switch to signed 16-bit integer in the future. 🤔

**Comment by ethouris** [comment]
Not sure how to do it in SRT. Likely in the connecting function, that's the only reasonable place, but yes, I agree this could at least allow us to add some trap representation or special values in future.

**Comment by maxsharabayko** [comment]
Might be worth adding to the docs.
"weight max value is 32767".
https://github.com/Haivision/srt/pull/1550/files#diff-c3acf7a2db7023ece66344377c9d3ceaR765

**Pull request merged**
