### PR TITLE
Fix deadlock condition

### LINKED ISSUE #41: Deadlock issue with tsbpd
So there's a deadlock issue in SRT. Here's all the info I got on it and how to reproduce.

My configuration: Windows 10 x64. I built SRT from my [`shared`](https://github.com/russelltg/srt/tree/shared) branch ( #35 ) with the only modification being adding a `srt_startup` call to the first line of main (didn't work otherwise) and commenting out line 3143 of core.cpp because it caused a crash in debug mode.  [Here's the diff file](https://github.com/Haivision/srt/files/1092677/working.txt)

Steps to reproduce: 

1. Start some sort of thing streaming over UDP. I just used VLC to stream a video
2. Start a `stransmit` process to send the data from that udp stream over SRT with the `-tsbpd` flag. 
3. Start another `stransmit` process to receive that data send from the first and send it over a different UDP port also with the `-tsbpd` flag
4. Startup something to check if that UDP data is being recieved. I used VLC.
5. Startup [clumsy](https://jagt.github.io/clumsy/) and add 5% packet loss and 80ms of lag over the UDP socket SRT is sending/recieving on. 

Here's a diagram:

image

Wait. Eventually the video will stop, and the sender process will close:

image

You can now attach a debugger to the process and you'll see that it's in deadlock:

One thread is trying to lock `m_RecvLock` on `core.cpp:4595`, with this call stack:
image
That same thread is holding the `m_RcvLossLock` mutex from `core.cpp:4553`.

A different thread is trying to lock `m_RcvLossLock` from `core.cpp:4876` with this call stack:

image

While that same thread is holding the `m_RecvLock` mutex from `core.cpp:1445`

They are both waiting on each other. 

Also this should be a supported scenario for SRT to run, it's all about handing latency and packet loss, so it's unfortunate that is crashes with any amount of either. 

Interestingly enough, it works fine if the latency is set to at least double the lag added in clumsy (the rtt).

### PR DESCRIPTION
**Pull request by russelltg**
This fixes #41 by making sure CUDT::processData doesn't hold two locks at the same time.

### CODE REVIEW

**Comment by rndi** [comment]
Hello @russelltg ,

I am not sure I like this solution even if it works. Could you please give further explanations on this change?

Much appreciated!

**Comment by russelltg** [comment]
This fix was suggested by @ethouris in #41. [Here's the link](https://github.com/Haivision/srt/issues/41#issuecomment-310330160) to the description of the fix.

**Comment by rndi** [comment]
Well... I don't see much of an explanation there. Meanwhile this change constitutes change in logic so I was hopping to get more details on logic change part.

**Comment by ethouris** [comment]
Sorry I haven't looked at it earlier. I confirm this fixes the deadlock problem. This solution was found by me first and Russel has retested it. Please submit.

**Comment by rndi** [comment]
Hello @ethouris ,

Please see [my comment](https://github.com/Haivision/srt/pull/49#issuecomment-310812338) above. What is the reason for changing signaling logic flow instead of simply fixing the deadlock issue?

Thanks

**Comment by russelltg** [comment]
That should fix the logic change. I just added another pair of `{}` to make sure the scoped lock is destroyed before `m_RecvLock` is locked.

**Comment by rndi** [comment]
Thank you @russelltg !

**Pull request merged**
