### PR TITLE
Added mbedtls encryption library choice for haicrypt

### PR DESCRIPTION
**Pull request by ethouris**
This includes:
 - slight changes in option handling for encryption library
 - added support for mbedtls choice as encryption library

Depends: #742 (merged already)

### CODE REVIEW

**Comment by jeandube** [comment]
So PR#742 is obsolete. By pre-merging 742 into this PR it is harder to review the changes, if any, to the CRYSPR framework to add mbedTLS.  I only realized this after the fact.

**Comment by ethouris** [comment]
@jeandube I didn't have a choice to include your PR. Review can be also done after your PR is merged to the mainline.

**Comment by maxlovic** [comment]
`USE_ENCLIB` -> `CRYPTLIB`?
`ENABLE_ENCRYPTION` now looks redundant. `CRYPTLIB=NONE`?

**Comment by ethouris** [comment]
Disabled encryption doesn't only select no encryption library, but turns off the encryption functionality in SRT (e.g. disallows to use `SRTO_PASSPHRASE` option).

**Pull request merged**
