### PR TITLE
Reshaped source files and applications. Preparations for splitting off tests.

### PR DESCRIPTION
**Pull request by ethouris**
The following changes are made:

1. The "common" directory no longer contains files used by other projects. This directory remains, but it contains parts used only on Windows, to provide compat, used independently by haicrypt and srtcore.
2. The "srtcore" directory now contains back all the parts used by it, as well as some reusable include files. The applications in "apps", "testing" and "examples" are allowed to "borrow" them.
3. The "apps" directory contains application files as well as shared components between applications. Applications from "testing" directory are allowed to "borrow" any of them.
4. The "examples" directory contains simple programs for rather educational purpose. This directory gets the UDT legacy applications "sendfile" and "recvfile".

### CODE REVIEW

**Comment by lars18th** [comment]
Hi @ethouris ,

In your PR you're lost my improvements in the statistics printout. See here for the rollback:
https://github.com/Haivision/srt/pull/270/files#diff-8f24b7298e72c9fa92b25e4c4e216d52

I feel that with the "movement" of files from one directory to the other (`common` to `testing`) you have used the ancient version of source files.

Can you fix it, please? :smile:

**Comment by ethouris** [comment]
@lars18th - I think that's not true, let me explain, it's a bit complicated.

The "transmitmedia" have been changed twofold:

1. There's made **a split**. The same file, so far, has been put under two locations, and effectively moved out of `common` directory into:
- `apps/transmitmedia*` (`transmitbase.hpp`, `transmitmedia.hpp`, `transmitmedia.cpp`)
- `testing/testmedia*` (`testmediabase.hpp`, `testmedia.hpp`, `testmedia.cpp`)

2. It should be stated that **continuation** for all apps from `apps` directory and the application-common files from `common` directory are all files under the same names residing all now in the `apps` directory. 

3. Git is stupid. Even though I have renamed explicitly `common/transmitmedia.cpp` -> `apps/transmitmedia.cpp`, and **only copied** this file additionally to `testing/testmedia.cpp`, it probably does not record the renaming event and takes some most probable event (file with the same name that was deleted and added afterwards - I'm guessing). If you take a look at the FILE RENAMING mentioned on top of this file difference on github that you have pointed to by your link, you'll see that it was moved to testing. This isn't true - this file has been moved to apps. But you'll see this file later simply as "a new file added to apps", which should be almost identical with the previous version, and obviously with your fixes included.

The goal of this change is that we have discovered that the interests and purpose of `stransmit` application have diverged. Users need a simple a flipper between SRT and UDP/CON/FILE, and `stransmit` has never been predicted for that purpose - it was just a simple tool for testing SRT. Roman has lately added many improvements that make stransmit a real user application (with fixed some problems and added some important features), however this required removal of some working modes and features that were needed for testing.

Therefore we decided to split the whole apps package into "apps" and "testing". The "testing" directory contains now all the old version of stransmit and accompanying files, and that's why you probably can see some older version without your fixes. It shouldn't matter for users, as this is only for handling several experimental and unstable things.

**Comment by ethouris** [comment]
Well, now that I merged with the latest upstream, all problems of showing renamed files incorrectly are somehow magically gone. This should look much better now.

**Comment by lars18th** [comment]
Hi @ethouris ,

Great to hear it! So, I hope to see soon this branch merged to the "dev" mainstream. :+1: 

Regards.

**Pull request merged**
