### PR TITLE
[core] Fix warning and workaround ABI compatibility due to ENABLE_EXPERIMENTAL_BONDING

### PR DESCRIPTION
**Pull request by quink-black**
The warning can be triggered when srt.h is included by other project.

### CODE REVIEW

**Comment by quink-black** [comment]
By the way, the abi is broken due to ENABLE_EXPERIMENTAL_BONDING.

**Comment by maxsharabayko** [comment]
> By the way, the abi is broken due to ENABLE_EXPERIMENTAL_BONDING.

Right, unfortunately, we've missed that.
Experimental bonding is disabled by default, so we should stay compliant at least with the default API. Thus `SRTO_BINDTODEVICE` should go right after `SRTO_PEERIDLETIMEO`, and followed by bonding related options.

**Comment by ethouris** [comment]
Fortunately option values are not significant for data interchange, problems may occur only for shared library updates.

**Comment by quink-black** [comment]
> > By the way, the abi is broken due to ENABLE_EXPERIMENTAL_BONDING.
> 
> Right, unfortunately, we've missed that.
> Experimental bonding is disabled by default, so we should stay compliant at least with the default API. Thus `SRTO_BINDTODEVICE` should go right after `SRTO_PEERIDLETIMEO`, and followed by bonding related options.

The patch is trying to make  SRTO_BINDTODEVICE compliant before ENABLE_EXPERIMENTAL_BONDING was added. Since almost half a year has passed, it make sense to not break the ABI again. So I can move SRTO_BINDTODEVICE before #if ENABLE_EXPERIMENTAL_BONDING.

**Comment by quink-black** [comment]
> Fortunately option values are not significant for data interchange, problems may occur only for shared library updates.

On the other hand, it's hard to detect and more dangerous.

**Comment by maxsharabayko** [comment]
> > Right, unfortunately, we've missed that.
> > Experimental bonding is disabled by default, so we should stay compliant at least with the default API. Thus `SRTO_BINDTODEVICE` should go right after `SRTO_PEERIDLETIMEO`, and followed by bonding related options.
> 
> The patch is trying to make SRTO_BINDTODEVICE compliant before ENABLE_EXPERIMENTAL_BONDING was added. Since almost half a year has passed, it make sense to not break the ABI again. So I can move SRTO_BINDTODEVICE before #if ENABLE_EXPERIMENTAL_BONDING.

[`SRTO_BINDTODEVICE`](https://github.com/Haivision/srt/blob/master/docs/APISocketOptions.md#SRTO_BINDTODEVICE) was first introduced in v1.4.2 together with `ENABLE_EXPERIMENTAL_BONDING`.

`ENABLE_EXPERIMENTAL_BONDING` is an experimental API extension, disabled by default, therefore `SRTO_BINDTODEVICE=56` is a better way out of this.

**Comment by quink-black** [comment]
> > > Right, unfortunately, we've missed that.
> > > Experimental bonding is disabled by default, so we should stay compliant at least with the default API. Thus `SRTO_BINDTODEVICE` should go right after `SRTO_PEERIDLETIMEO`, and followed by bonding related options.
> > 
> > 
> > The patch is trying to make SRTO_BINDTODEVICE compliant before ENABLE_EXPERIMENTAL_BONDING was added. Since almost half a year has passed, it make sense to not break the ABI again. So I can move SRTO_BINDTODEVICE before #if ENABLE_EXPERIMENTAL_BONDING.
> 
> [`SRTO_BINDTODEVICE`](https://github.com/Haivision/srt/blob/master/docs/APISocketOptions.md#SRTO_BINDTODEVICE) was first introduced in v1.4.2 together with `ENABLE_EXPERIMENTAL_BONDING`.
> 
> `ENABLE_EXPERIMENTAL_BONDING` is an experimental API extension, disabled by default, therefore `SRTO_BINDTODEVICE=56` is a better way out of this.

Is the updated patch OK? Or you mean SRTO_BINDTODEVICE should be assigned a value explicitly?

**Review by maxsharabayko — APPROVED** [review]
> Is the updated patch OK?

Yes, all good. Thank you!

**Pull request merged**
