### PR TITLE
Fix MINGW build.

### PR DESCRIPTION
**Pull request by jlsantiago0**
Fix MINGW build.

### CODE REVIEW

**Comment by ethouris** [comment]
Just a question: did you check this on MinGW native and through linux cross?

**Comment by jlsantiago0** [comment]
Building via MINGW cross compiler on a Linux host.

**Comment by ethouris** [comment]
If you could take a look at #439 as well... We're getting some complaints about MinGW platform once per a time and each time someone comes up with a solution that later turns out to hurt another MinGW user or sometimes other systems. I'd welcome someone to make things eventually clean on this platform.

**Comment by jlsantiago0** [comment]
@ethouris Tested the patch and it works fine for me.

**Pull request merged**
