### PR TITLE
Rename srtcore/ to srt/

### PR DESCRIPTION
**Pull request by ocrete**
This way, one can use srt without having to install it, it makes it
easier to use it as a subproject in the same way that you could use it as an
independent build.

### CODE REVIEW

**Comment by ethouris** [comment]
What's the problem of installing it in a local build directory and using it from there, in order to submit it to a superproject? Kinda:

```
PROJECT> cd srt
PROJECT/srt> ./configure --prefix=install
PROJECT/srt> make && make install
PROJECT/srt> cd ..
PROJECT> ./configure --with-srt=srt/install
```

?

**Comment by ethouris** [comment]
On the other hand I admit, I don't know whether there is any reasonable standard in cmake to handle a subproject-superproject relationship. Usually they advice to use `add_subdirectory`, but this actually dips the subproject into superproject rules, which in several cases causes extra mess, especially with the common variables.

**Comment by maxlovic** [comment]
Example usage from a submodule with CMake:
```
SET(ENABLE_SHARED OFF)
add_subdirectory(submodule/srt)

SET(SRT_INCLUDE_DIR
	${CMAKE_SOURCE_DIR}/submodule/srt/srtcore
	${CMAKE_BINARY_DIR}/submodule/srt
	${CMAKE_SOURCE_DIR}/submodule/srt/common
	${CMAKE_SOURCE_DIR}/submodule/srt/haicrypt
)

target_include_directories(TARGET_APP PUBLIC
	${SRT_INCLUDE_DIR}
	${SRT_UTILS_INCLUDE_DIR}
	${PTHREAD_INCLUDE_DIR}
	)
```

After that you can use `#include "srt.h"` in the `TARGET_APP`.
Do you want to have `#include "srt/srt.h"` instead?

**Comment by ocrete** [comment]
Exactly, I was to use srt/srt.h, because the same code can also be built against the installed one (the normal Linux case), but on Windows/etc, we can't rely on the system, so it's easier if we build everything in one go.

I'm actually using Meson as the main build system, and it has the ability to use CMake subprojects,  and it also has the ability to use subprojects only as a fallback.

Ref:
https://gitlab.freedesktop.org/ocrete/gst-build/commit/29009847ee868523c14a3706aa40b3567e0fe1c1
https://gitlab.freedesktop.org/ocrete/gst-plugins-bad/commit/e0736b37b9f1449c04e3f5aaff989c13fa76b5ea

**Comment by maxlovic** [comment]
@ocrete What do you think about possible undesired inclusions. For example, you might have SRT installed, but you want to include headers from your local copy of SRT. Now you have the same naming and more chances to include the installed headers instead.

**Comment by ocrete** [comment]
Including the wrong thing is always a possibility with this.

One trick is to have the "installed" version in a specific dir (something like `/usr/include/srt-1/srt/srt.h`) .. and in your .pc file you put `/usr/include/srt-1`, which means that to compile against the installed one, you need to put `-I/usr/include/srt-1` so you have a bit more certainty.

**Comment by justinjoy** [comment]
May I ask you to resume the discussion? That's the way to have different versions in a system, too.

**Comment by maxlovic** [comment]
A certain blocker at the moment is that this PR conflicts with all of the rest queued pull requests. So if we merge it, conflicts will have to be resolved in other PRs.

But we need to come up with a bottomline of pros and cons in the form of a list.

> That's the way to have different versions in a system, too.

@justinjoy With CMake you can specify the `-DCMAKE_INSTALL_PREFIX=<destination_path>` and `make install` will copy all the files to that desired location.

Don't get me wrong, I am not against this change. The intent is to clearly understand whether it is worth changing the folder name, and how would the usage experience improve in that case?

**Comment by justinjoy** [comment]
> A certain blocker at the moment is that this PR conflicts with all of the rest queued pull requests. So if we merge it, conflicts will have to be resolved in other PRs.

The more SRT becomes active, the more conflicts there will be.

> @justinjoy With CMake you can specify the `-DCMAKE_INSTALL_PREFIX=<destination_path>` and `make install` will copy all the files to that desired location.

We can also use DESTDIR too if we just want to place it on different directory.
The reason to need different location is same as @ocrete's comment.

>> Including the wrong thing is always a possibility with this.

In any case, `/usr/include/srt/srt.h` will cause mistake from time to time.

> Don't get me wrong, I am not against this change. The intent is to clearly understand whether it is worth changing the folder name, and how would the usage experience improve in that case?

From the user's point of view, nothing will change.
but if someone wants to use SRT as submodule, it can help prevent mistake.

for example, let's assume that we installed srt on ubuntu by `apt-get`.
Now I have `/usr/include/srt/srt.h`.
If I want to use my local srt in `~/dev/srt/srtcore/srt.h`, I should use `-I~/dev/srt/srtcore/`.
Even I missed add this `-I`, my compiler will not complain of missing `srt.h` because it already finds `srt.h` in `/usr/include`.
So @ocrete mentioned `-I/usr/include/srt-1/`.

If srt is installed by package manager, and `srt.h` is in `/usr/include/srt-1/srt/`, the path of `srt.h` will be returned only by `pkg-config` or similar tools. Then, it prevents user mistake like above.

From a package management perspective, `/usr/include/srt/srt.h` is problematic if there's another package which provides `srt.h`,too.  It will not be able to be installed at the same time or it will make confusion to find `srt.h` from different packages, even though they are not relevant.

This concept is well explained in [parallel installability](https://developer.gnome.org/programming-guidelines/stable/parallel-installability.html.en), although the document assumes the ABI breaking situation.

**Comment by ocrete** [comment]
Another option is to create a `include` dir inside the repo and just move the installed headers into `include/srt/srt.h`, etc and leave `srtcore/`as-is.

**Comment by ocrete** [comment]
I created PR #825 which the other approach. I've never been a fan of separate "include" dirs, but it does make it easier to switch

**Comment by ethouris** [comment]
For me, all of these solutions are wrong.

How about creating the `srt` directory inside `srtcore` and put all public headers there?

This is important because:
* public headers may have dependencies on one another
* By adding the include directory as the `srtcore` directory you have
    * Correct path for `#include <srt/srt.h>`
    * Also access to devel headers, if needed by the apps

**Comment by justinjoy** [comment]
> For me, all of these solutions are wrong.
> 

No, it shouldn't be wrong. Rather, it follows normal implicit rules of directory structure like the other open source did.

> How about creating the `srt` directory inside `srtcore` and put all public headers there?

Let me explain more. Just think about `-I` option of compiler to build `app` with the current structure like the below drawing.

```
project(srt directory) -+- srtcore
                        |
                        +- apps
```

In `apps` directory, This perhaps needs `-I../srtcore`, but as this PR pointed out, `#include <srt/srt.h>` is not possible.

If we change `srtcore` to `srt`, it simply achieves what we want with `-I../` in `apps` directory.
However, according to your suggestion, we have to have different `-I` option per source directories. For example, to build sources in `srtcore`, it needs `-I.` in `srtcore` directory, but for `apps`, it requires `-I../srtcore`. Why do you think adding complexity is better?

If the purpose of this suggestion is to avoid conflictions, more common way which the other open-source was doing has already been suggested in #825.

**Comment by ethouris** [comment]
> > How about creating the `srt` directory inside `srtcore` and put all public headers there?
> 
> Let me explain more. Just think about `-I` option of compiler to build `app` with the current structure like the below drawing.
> 
> ```
> project(srt directory) -+- srtcore
>                         |
>                         +- apps
> ```
> 
> In `apps` directory, This perhaps needs `-I../srtcore`, but as this PR pointed out, `#include <srt/srt.h>` is not possible.

What isn't possible? When we have `ROOT/srtcore/srt/srt.h` location then with `-I../srtcore` the instruction `#include <srt/srt.h>` is exactly the right one.

> If we change `srtcore` to `srt`, it simply achieves what we want with `-I../` in `apps` directory.

But this way we need to have a name that is a compromise between usability and comprehension. Wrong approach.

> However, according to your suggestion, we have to have different `-I` option per source directories. For example, to build sources in `srtcore`, it needs `-I.`

Somehow it compiles now without this option.

> ... in `srtcore` directory, but for `apps`, it requires `-I../srtcore`. Why do you think adding complexity is better?

The `-I../srtcore` option is exactly what is there right now, and it's the right approach for applications, which **are not part of the library**.

What we need to change here is to make all inclusions of `srt.h` to sound like `#include <srt/srt.h>`, and this only makes things consistent with everything else.

> If the purpose of this suggestion is to avoid conflictions, more common way which the other open-source was doing has already been suggested in #825.

The proposal to add an "include" directory is too radical. We've been through this already, it was a horror, and I really wouldn't like to return to this.

**Comment by justinjoy** [comment]
> > > How about creating the `srt` directory inside `srtcore` and put all public headers there?
> > 
> > 
> > Let me explain more. Just think about `-I` option of compiler to build `app` with the current structure like the below drawing.
> > ```
> > project(srt directory) -+- srtcore
> >                         |
> >                         +- apps
> > ```
> > 
> > 
> > In `apps` directory, This perhaps needs `-I../srtcore`, but as this PR pointed out, `#include <srt/srt.h>` is not possible.
> 
> What isn't possible? When we have `ROOT/srtcore/srt/srt.h` location then with `-I../srtcore` the instruction `#include <srt/srt.h>` is exactly the right one.

I said **the current structure**.

> 
> > If we change `srtcore` to `srt`, it simply achieves what we want with `-I../` in `apps` directory.
> 
> But this way we need to have a name that is a compromise between usability and comprehension. Wrong approach.

In similar, that's the reason the other projects has subsubdirectories. Take a look at the structure of *GLib* project.

> > However, according to your suggestion, we have to have different `-I` option per source directories. For example, to build sources in `srtcore`, it needs `-I.`
> 
> Somehow it compiles now without this option.

Because this repo has been made to be built in the current directory structure.

> 
> > ... in `srtcore` directory, but for `apps`, it requires `-I../srtcore`. Why do you think adding complexity is better?
> 
> The `-I../srtcore` option is exactly what is there right now, and it's the right approach for applications, which **are not part of the library**.

That's not a point. *Not a part of the library* isn't related to have `-I../` or `-I../srtcore`.
What you need to say *Not a part of the library* is just not to install them into `lib` directory.

> 
> What we need to change here is to make all inclusions of `srt.h` to sound like `#include <srt/srt.h>`, and this only makes things consistent with everything else.
> 
> > If the purpose of this suggestion is to avoid conflictions, more common way which the other open-source was doing has already been suggested in #825.
> 
> The proposal to add an "include" directory is too radical. We've been through this already, it was a horror, and I really wouldn't like to return to this.

Not sure what you are exactly concerned. To be honest, I don't see the differences between your suggestion and #825. They are equally the same *too radical* perspective.

For me, you seem to want to set srt-specific policy.

**Comment by ethouris** [comment]
> > > If we change `srtcore` to `srt`, it simply achieves what we want with `-I../` in `apps` directory.
> > 
> > But this way we need to have a name that is a compromise between usability and comprehension. Wrong approach.
> 
> In similar, that's the reason the other projects has subsubdirectories. Take a look at the structure of _GLib_ project.

The motivation for subdirectories is to have logical subproject breakdown with directories logically named thereafter. Same here.

> > > However, according to your suggestion, we have to have different `-I` option per source directories. For example, to build sources in `srtcore`, it needs `-I.`
> > 
> > Somehow it compiles now without this option.
> 
> Because this repo has been made to be built in the current directory structure.

Yes, and this concept isn't going to change it.

> > > ... in `srtcore` directory, but for `apps`, it requires `-I../srtcore`. Why do you think adding complexity is better?
> > 
> > The `-I../srtcore` option is exactly what is there right now, and it's the right approach for applications, which **are not part of the library**.
> 
> That's not a point. _Not a part of the library_ isn't related to have `-I../` or `-I../srtcore`.
> What you need to say _Not a part of the library_ is just not to install them into `lib` directory.

Not part of the library is exactly what I meant. An application lying together in the same project as
the library is not part of it, but a subproject that is dependent on another subproject. So the include
path to `-I../srtcore` is something that will apply to all kinds of applications being compiled there.
Moreover, even adding `-I../srtcore` to the SRT library build rules - although reasonless - won't disturb.

> > The proposal to add an "include" directory is too radical. We've been through this already, it was a horror, and I really wouldn't like to return to this.
> 
> Not sure what you are exactly concerned. To be honest, I don't see the differences between your suggestion and #825. They are equally the same _too radical_ perspective.

From the user's perspective maybe so, but not from the developer's perspective. 

> For me, you seem to want to set srt-specific policy.

I haven't seen any "standard policy" in open-source projects and there were always various approaches. Every project may have their own specifics.

For example: in ffmpeg you have various directories that are subprojects and simultaneously these directory names will be also sub-include directory names after installation of the headers.

However, there's no `ffmpeg` sub-include directory. Probably because they don't have anything like a "central header for everything".

We do.

What we want to achieve is to make the users' life easier by allowing apps to reach directly to SRT library dependency without installing it. Moving the public headers into a sub-directory `srt` inside `srtcore` satisfies this need without making developers' life harder.

**Comment by justinjoy** [comment]
If you don't want, please close or lockdown issue not to waste time each other.

**Comment by maxsharabayko** [comment]
This PR is outdated. Issue #1621 was created to track the request.
Closing the PR.

**Pull request closed without merging**
