### PR TITLE
Fix libsrt library install_name in macOS

### PR DESCRIPTION
**Pull request by ylatuya**
MACOSX_RPATH is explicitly disabled, in that case the library should at least have as install_name the output directory where it's installed.

### CODE REVIEW

**Comment by rndi** [comment]
@ylatuya , @ethouris ,

Is there a good reason to have MACOSX_RPATH explicitly disabled? The change was introduced as part of HSv5 mega-commit with no explanations given: https://github.com/Haivision/srt/commit/c91d5f7e4139c5e8316a189446499bc3ee46915b. I would probably want to roll that change back unless a reasonable explanation is found since having MACOSX_RPATH "ON" is the recommended default: https://cmake.org/cmake/help/v3.0/prop_tgt/MACOSX_RPATH.html

**Comment by ylatuya** [comment]
There are 3 options with respect of the library's install_name:
 1. Current one using only the library name: `librst.1.dylib`
 2. Proposed patch using the prefix: `<PREFIX>/lib/libsrt.1.dylib`
 3. Using `@rpath`: `@prath/libsrt.1.dylib` 

I can't find a good reason for using option 1 as it won't work in most of the cases.

Option 2 would make sense if librst was provided as an OS X framework with a fix installation path (eg: /Library/Frameworks/SRT.framework). It's the option most project use since in macOS, devs are used to either building using as prefix the final installation path or relocating libraries.

Option 3 is the most portable one, it's not a silver bullet but it will work in most cases even if the library is not relocated.

Maybe these changes were made for the iOS build that changes the install_name dir to @executable_path/Frameworks ? https://github.com/Haivision/srt/blob/master/scripts/iOS.cmake#L88

**Comment by alexpokotilo** [comment]
@rndi you are right MACOSX_RPATH disabled in c91d5f7 committed on Sep 7, 2017,
@ylatuya But https://github.com/Haivision/srt/blob/master/scripts/iOS.cmake#L88 committed on Mar 16, 2018. So MACOSX_RPATH disabled not per IOS commit as it's disabled before it.
I've asked @Gummilion to build and test IOS without **set(MACOSX_RPATH OFF)**  in  CMakeLists.txt.
He will reply here after his tests.

**Comment by ylatuya** [comment]
Sorry, this last update is not complete, do not merge.

**Comment by ylatuya** [comment]
All good! I have tested in the GStreamer macOS builds and linking to the new library make the plugin load correctly now. See https://gitlab.freedesktop.org/gstreamer/cerbero/issues/63 for more context

**Pull request merged**
