### PR TITLE
[core] Fixed problem with handling the lingering links case in non-blocking group reader

### PR DESCRIPTION
**Pull request by ethouris**
The problem is described in #1805, though may need further testing.

This PR also contains a fix for lock ordering at the handshake, might need to be moved.

### CODE REVIEW

**Comment by ethouris** [comment]
This remains as draft due to enclosing two different solutions. The fix for wrong lock on `m_ControlLock` was necessary for proper testing the problem. The fix for wrong epoll update has been tested by the issue reporter.

**Comment by gou4shi1** [comment]
why not merge this pr?

**Comment by ethouris** [comment]
I remerged this with latest upstream; the fix for the deadlock on ConnectionLock is already merged. The remaining thing is the avoidance of the spurious read-ready for group.

**Comment by gou4shi1** [comment]
Great, I found your atomic PR is merged, so this PR is unblocked now?

> The remaining thing is the avoidance of the spurious read-ready for group.

The remaining part I care is just `if (ready_sockets.empty())) throw CUDTException();` LOL

**Comment by maxsharabayko** [comment]
Closed by #2203

**Pull request closed without merging**
