### PR TITLE
Move installed headers to their own directory

### PR DESCRIPTION
**Pull request by ocrete**
This way, one can use srt without having to install it, it makes it
easier to use it as a subproject in the same way that you could use it as an
independant build.

This should have similar results for #795, but with less disruption for existing pull requests.

### CODE REVIEW

**Comment by justinjoy** [comment]
@maxlovic Do you think this PR still problematic to keep history of changes?
Then, how about creating a symbolic link(srtcore -> srt) in compile time by CMake?

**Comment by maxlovic** [comment]
I think #795 is better. This one is a half way solution, and not very neat.

**Comment by ocrete** [comment]
This one has the advantage of making it very clear which headers are public/installed and which are not.  But I don't have a strong opinion either way

**Comment by maxsharabayko** [comment]
This PR is outdated. Issue #1621 was created to track the request.
Closing the PR.

**Pull request closed without merging**
