### PR TITLE
fix bug when pack loss

### PR DESCRIPTION
**Pull request by xiaozhihong**

### CODE REVIEW

**Comment by maxsharabayko** [comment]
Hi, @xiaozhihong 
The existing formula `(time_now - RTT + 4RTTVar)` is intended to be so.

The idea is that all loss reports that arrive within `RTT - 4RTTVar` are ignored because they are likely sent before retransmission has reached the receiver.
But if a loss report arrives after approximately one RTT, then the retransmission was likely lost. Due to the variance of RTT, a valid loss report may come a bit earlier, therefore we subtract RTT variance.

**Comment by xiaozhihong** [comment]
> approximately

RTT + 4RTTVar means RTO, what's the meaning of 'RTT - 4RTTVar'? If I

**Comment by xiaozhihong** [comment]
`RTT + 4RTTVar` means RTO, any rexmit must <= RTO, this is my view. I can't understand what the meaning of `RTT - 4RTTVar`.

**Comment by maxsharabayko** [comment]
Fair point.
However, RTO in SRT is rather `RTT + 4×RTTVar + 2×10ms`, where 10 ms is the period of ACK packets.

In this `packLostData(..)` function is not exactly RTO that is used. Unfortunately, the algorithm is not documented yet.

In short, there is a loop over loss records. Each iteration removes a recond (`m_pSndLossList->popLostSeq()`).
Each ~RTT/2 a Periodic NAK is expected to arrive. See the ["Packet retransmission"](https://tools.ietf.org/html/draft-sharabayko-mops-srt-01#section-4.8.2) section of RFC.
The goal is to ignore a periodic loss report that arrives RTT/2 after a packet was already retransmitted, but take into account a loss record that arrived around one RTT after a packet was retransmitted.

If `RTT + 4×RTTVar` was used, then only a loss report that arrives after 3/2×RTT would be considered.

It is done so mostly to optimize the work with the current implementation of the sender's loss list, and do not iterate over it each time to find a packet for retransmission.
A better way would be to repeat retransmission after RTO, but then the loss list should rather be a heap with the first packet to be retransmitted on top of it.

**Comment by xiaozhihong** [comment]
> periodic

Hi, thanks for your reply.
I found the code ` m_iNakReportAccel = 2;`. In live mode's transmit algorithm, the interval of rexmit must relate to m_iNakReportAccel?

**Comment by maxsharabayko** [comment]
@xiaozhihong  This "acceleration" is applied [here](https://github.com/Haivision/srt/blob/master/srtcore/core.cpp#L7996) on the periodic NAK (loss report) interval value `RTT + 4×RTTVar`, effectively dividing it by two.

**Comment by maxsharabayko** [comment]
Closing as the existing formula is correct. Won't merge.

**Pull request closed without merging**
