### PR TITLE
[core] Made offset consistent with avail_bufsize.

### PR DESCRIPTION
**Pull request by gou4shi1**
Ref: https://github.com/Haivision/srt/pull/2467#issuecomment-1263702682

### CODE REVIEW

**Comment by maxsharabayko** [comment]
One of the changes has been introduced in #2463.
I believe the remaining one is not correct. The available RCV buffer size has to be counted from the acknowledgment position.
The value is sent in the ACK packet back to the sender (required protocol behavior), as well as in SRT stats (not much sense to change the behavior).

**Comment by maxsharabayko** [comment]
In fact, I think using `m_iRcvLastSkipAck` for the `strFullnessState(..)` is also incorrect, because ACK position is needed instead of the drop position. I missed that one reviewing #2463. So I guess that very change has to be reverted.

**Comment by gou4shi1** [comment]
> One of the changes has been introduced in #2463.

Oops, my mistake, lol.

**Comment by gou4shi1** [comment]
Then the `m_iRcvLastSkipAck` in
```
LOGC(qrlog.Error, log << CONID() << "SEQUENCE DISCREPANCY. BREAKING CONNECTION." " seq=" << rpkt.m_iSeqNo << " buffer=(" << m_iRcvLastSkipAck << ":" << m_iRcvCurrSeqNo // -1 = size to last index << "+" << CSeqNo::incseq(m_iRcvLastSkipAck, int(m_pRcvBuffer->capacity()) - 1)
```
should also be changed?

**Comment by maxsharabayko** [comment]
> Then the `m_iRcvLastSkipAck` in
> 
> ```
> LOGC(qrlog.Error, log << CONID() << "SEQUENCE DISCREPANCY. BREAKING CONNECTION." " seq=" << rpkt.m_iSeqNo << " buffer=(" << m_iRcvLastSkipAck << ":" << m_iRcvCurrSeqNo // -1 = size to last index << "+" << CSeqNo::incseq(m_iRcvLastSkipAck, int(m_pRcvBuffer->capacity()) - 1)
> ```
> 
> should also be changed?

Good catch!
Yes, here `m_iRcvLastAck` should be used instead of `m_iRcvLastSkipAck`. To have the same base with `getAvailRcvBufferSizeNoLock()` called above.

**Comment by gou4shi1** [comment]
ping

**Pull request merged**
