### PR TITLE
[core] remove MSG_TRUNC logging

### PR DESCRIPTION
**Pull request by robUx4**
It broke in #849

### CODE REVIEW

**Comment by ethouris** [comment]
Wait a minute. If `MSG_TRUNC` is not defined, how do you know that the networking system is using it at all?

And no, this can't be done this way. If there is no header file to provide this value on particular system, then the whole code that uses it should be conditionally blocked on that system.

**Comment by robUx4** [comment]
> And no, this can't be done this way. If there is no header file to provide this value on particular system, then the whole code that uses it should be conditionally blocked on that system.

OK. It's only used to log a value. I can get around that.

**Comment by robUx4** [comment]
> @robUx4 Are you sure it was broken in #849? It seems unrelated. What is the system and compiler you are testing on?

No I'm not sure because the CI seems to be happy with the code. I don't know where the `MSG_TRUNC` is magically coming from when compiling with mingw-w64.

I'm using mingw-w64 and since that commit we had to use a [patch to get around this](https://code.videolan.org/videolan/vlc/-/blob/master/contrib/src/srt/0001-core-ifdef-MSG_TRUNC-nixes-fix.patch) in VLC.

**Comment by ethouris** [comment]
I think it can be just as well fixed by simply displaying the value of the flags in hex, and remove displaying the value of `MSG_TRUNC`. This `MSG_TRUNC` symbol is used only to allow to compare this visually in the log, but this isn't necessary.

According to the system's specification there should be no flags set in the described situation and if this happens it's a system bug. As such a bug was once seen, there's prepared a workaround for it; the value of the flag is worth printing in hex in the log, but that's all. A developer may still determine what this is, by this hex value, and compare to whatever they have in the system.

**Comment by robUx4** [comment]
> I think it can be just as well fixed by simply displaying the value of the flags in hex, and remove displaying the value of MSG_TRUNC. 

The flag is already displayed (line above). So I'll remove remove the `MSG_TRUNC` display (easy to find it's 0x20 on Linux).

**Review by maxsharabayko — APPROVED** [review]

**Pull request merged**
