### PR TITLE
Extracted utilities to a separate file

### PR DESCRIPTION
**Pull request by ethouris**
Replaces #1007

### CODE REVIEW

**Comment by maxsharabayko** [comment]
Why not updating #1007 instead?

**Comment by ethouris** [comment]
Per reviewers' request, the PR is still one, but split into two separate commits:
1. Only moved some functions to a separate file.
2. Applied appropriate changes in the functions after moving.

**Comment by maxsharabayko** [comment]
So this PR only moves certain functions into a separate file, without changing the functions, right?

**Comment by ethouris** [comment]
Logically, yes. Some formal changes are only applied because simple moving of the functions wouldn't be correct OOTB.

**Pull request merged**
