### PR TITLE
[build] Added compile_commands.json to .gitignore

### PR DESCRIPTION
**Pull request by gou4shi1**
Let CMake generate Compilation Database for LSP editor plugins.

### CODE REVIEW

**Comment by maxsharabayko** [comment]
Can't this flag be passed to CMake explicitly?
Like `cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON`

**Comment by gou4shi1** [comment]
> Can't this flag be passed to CMake explicitly?

sure, I just think it's a common requirement, LOL

**Comment by gou4shi1** [comment]
and It's useful to gitignore `compile_commands.json`

**Comment by quink-black** [comment]
You can set the CMAKE_EXPORT_COMPILE_COMMANDS environment variable so it works for all cmake projects.

```
export CMAKE_EXPORT_COMPILE_COMMANDS=ON
```

Approve for adding compile_commands.json to gitignore.

**Pull request merged**
