### PR TITLE
[core] drop packets in the new recv buffer by group recv base

### PR DESCRIPTION
**Pull request by gou4shi1**
Fix https://github.com/Haivision/srt/pull/1964#issuecomment-986610218
* `CUDT::dropToGroupRecvBase()` is not placed in `CUDT::tsbpd()` (as [what I have done for the old recv buffer](https://github.com/Haivision/srt/pull/2026)) since this behavior is not related to tsbpd and should also work for message mode.
* `CUDT::dropToGroupRecvBase()` is placed in `sendCtrlAck()` since I can't find another better place.
* Some asserts are erased from `CRcvBufferNew::dropUpTo()` since we need to drop non-empty packets now.
* Update `m_numOutOfOrderPackets` and `m_iFirstReadableOutOfOrder` in `CRcvBufferNew::dropUpTo()` since we need to drop non-empty packets now.

### CODE REVIEW

**Comment by gou4shi1** [comment]
any comment？

**Comment by maxsharabayko** [comment]
Could you remind me why do we need to drop packets somewhere else apart from when we are reading from the group?
I am not quite sure about placing it in the `sendCtrlAck()`.

**Comment by gou4shi1** [comment]
> Could you remind me why do we need to drop packets somewhere else apart from when we are reading from the group?

sure, you can ref to this comment https://github.com/Haivision/srt/issues/1805#issuecomment-785260692

**Comment by maxsharabayko** [comment]
> For example, my group had two members: `A` and `B`.
In one `recv()` call, `A` was horse, `B` was elephant, `m_RcvBaseSeqNo` was 100, but `B` only had packets up to 95.
After a while, `B` received packets from 96-110, but `A` didn't  receive any packet ready to play.
As a result, the `tsbpd()` of `B` still tried to `PLAYING 96`, and the `group->updateReadState()` failed.

I see. The new receiver buffer does not wait for a packet to be acknowledged to deliver it. Thus I am not sure about placing the "drop to group state" logic in `sendCtrlAck()`. But I get your point why you don't want it to be in the TSBPD thread neither: this thread does not exist if TSBPD is disabled, meaning the plain message mode will still have the issue.

**Comment by gou4shi1** [comment]
> The new receiver buffer does not wait for a packet to be acknowledged to deliver it. Thus I am not sure about placing the "drop to group state" logic in `sendCtrlAck()`

Do you mean that you want to decouple ack logic and recv_buffer?

**Comment by maxsharabayko** [comment]
> Do you mean that you want to decouple ack logic and recv_buffer?

It has been already decoupled with the new receiver buffer.

**Comment by gou4shi1** [comment]
Hi, @maxsharabayko, I have made some changes, plz help to take a look:
* rebase on #2214, so that `dropToGroupRecvBase()` can just call `dropTooLateUpTo()`
* also update `m_iRcvCurrSeqNo` in `dropToGroupRecvBase()`, so that I don't need to change `sendCtrlAck()` too much.

**Comment by gou4shi1** [comment]
I found that `CRcvBufferNew::dropMessage()` doesn't update `m_numOutOfOrderPackets` and `m_iFirstNonreadPos`, therefore `readMessage()` after `dropMessage()` may be problematic.
My proposal is to call `CRcvBufferNew::dropUpTo()` if the requested to drop message contains `m_iStartPos`.
So `CRcvBufferNew::dropUpTo()` should be able to drop non-empty units as this PR done.

**Comment by gou4shi1** [comment]
I found out another solution: call `dropTooLateUpTo()` in `Group::recv()`.
It also need `dropUpTo()` to be able to drop non-empty units, maybe I should change this PR to only change the behavior of `dropUpTo()`, and change `Group::recv()` in the next PR.

**Comment by gou4shi1** [comment]
> I found out another solution: call `dropTooLateUpTo()` in `Group::recv()`.

It's done in #2218, it's still a draft to let you can take a look, I will have more tests again it.

**Comment by gou4shi1** [comment]
I found that dropping (fake ack) packets that not yet received may cause sender broken, e.g.
```
    if (CSeqNo::seqcmp(ackdata_seqno, CSeqNo::incseq(m_iSndCurrSeqNo)) > 0)
    {
        leaveCS(m_RecvAckLock);
        // this should not happen: attack or bug
        LOGC(gglog.Error,
                log << CONID() << "ATTACK/IPE: incoming ack seq " << ackdata_seqno << " exceeds current "
                    << m_iSndCurrSeqNo << " by " << (CSeqNo::seqoff(m_iSndCurrSeqNo, ackdata_seqno) - 1) << "!");
        m_bBroken        = true;
        m_iBrokenCounter = 0;
        return;
    }
```

**Comment by gou4shi1** [comment]
> Thus I am not sure about placing the "drop to group state" logic in `sendCtrlAck()`.

I have extracted the change to `dropUpTo()` into #2221, it this part is acceptable, you can review #2221 firstly :)

> I found that ack packets over `m_iRcvCurrSeqNo` may break senders, e.g.

fixed

**Comment by gou4shi1** [comment]
Thanks for merging #2222, but I'm curious about why #2222 closed this PR?
Maybe my messy chat history is a little bit confused.
To summarize ,this PR is to solve the issue mentioned in https://github.com/Haivision/srt/issues/1805#issuecomment-785260692
And I found that receivers can not drop packets over `m_iRcvCurrSeqNo`, so only dropping in `Group::recv()` is not enough.
#2222 only to fix the issue I mentioned in this comment https://github.com/Haivision/srt/pull/2207#issuecomment-1002916763

**Comment by maxsharabayko** [comment]
> Thanks for merging #2222, but I'm curious about why #2222 closed this PR?

The keyword "fix" followed by issue or RP number in the description of the issue/PR i[s recognized by GitHub](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword), and automatically closes the relevant PR/issue.
PR #2222 has the following in its description: "Fix #2207".

**Pull request merged**
