### PR TITLE
Replaced pthread_mutex_t and pthread_cond_t usage by C++-11 constructions

### PR DESCRIPTION
**Pull request by ThomasVolkert**
This patch prepares the removal of pthread usages/dependencies.
Advantages:
- simpler overall setup (esp. on Windows this eases the setup of a compile/dev. environment)
- benefit from C++-11 cross-platform implementation and abstractions (could also solve problems with pthread which were described in the source code)
- more compact source code

If you accept this part, we can help to also replace the usage of pthread_t and other pthread parts.
This work is funded by CineMassive displays.

### CODE REVIEW

**Comment by alexpokotilo** [comment]
Hi @ThomasVolkert,
what about old Linuxes without C++11 support like CentOS 6, Ubuntu 12, Debian 7 ?
Default gcc for these OSes doesn't support for C++11.
I'm not sure about C++11 support for IOS and Android builds as well. Have you tested mobile builds ?

2 Moderators,
It's a good idea to move to modern C++11 features in general but we need to make sure we still have mobile builds working as well as understand that old Linux distros support is not necessary.

CentOS 6 is still in use BTW.

**Comment by rndi** [comment]
Hello @ThomasVolkert , and you very much for the patch!

Unfortunately, Alex P. is 100% correct and we are not ready to move to C++11 because we have a non-negotiable requirement for the main library to support a number of legacy platforms that are still in production and that are C++03 max.

Having said that, there are other ways of removing pthread library use on Windows if that is your main concern. Is that something you would be willing to explore?

**Comment by ethouris** [comment]
@ThomasVolkert If we were ready for C++11, lots of much more of improvements would have been done already. Unfortunately we still have requirements from other platforms and systems where a C++11-capable compilers are unavailable or by the reason some other requirements they can't be used. Effectively we are currently stuck with C++03.

I was thinking some time ago about some "C++11-alike" thread library (working with C++03) to replace the POSIX-thread API. If you can find something like that and add it here, it will be much more probable that it would be added to the current SRT code.

There is, for example, boost::thread, but we don't want to use it as it has significant differences to the C++11 standard thread library, so future switching to standard-library threads after we at some point move to a newer standard could be problematic.

**Comment by ethouris** [comment]
@ThomasVolkert There is one more thing very important when considering a change like this. At some point it was necessary for the development work to introduce the thread logging (to allow determine possible deadlocks by seeing which thread has acquired which mutex at which relation to other activities). Therefore there was needed a bigger wrapper for threads and a complete replacement of all API. There's a development work partially complete and thread logging is one of the parts, this one is considered more-less ready. You can take a look so that you can see where exactly the real POSIX API for threads would have to be replaced.

https://github.com/ethouris/srt/tree/dev-groups-thread-logging

**Comment by maxsharabayko** [comment]
This PR is no longer relevant. Refer to #1103.

**Pull request closed without merging**
