### PR TITLE
[core] make Loggers static

### PR DESCRIPTION
**Pull request by boxerab**
static variables are initialized before main() is invoked.
This early initialization fixes the crash in OBS, which was
related somehow to global Logger variable initialization

### CODE REVIEW

**Comment by boxerab** [comment]
Can someone please advise on why only Appveyor debug tests failed and everything else passes ?

**Comment by maxlovic** [comment]
@boxerab 
> Can someone please advise on why only Appveyor debug tests failed and everything else passes ?

Don't worry. We have one unit test with strict restrictions. That is the one that fails the AppVeyor validation. Nothing to do with your changes.

**Comment by boxerab** [comment]
Thanks @maxlovic

**Comment by boxerab** [comment]
The way I've refactored the code, the static loggers are initialized the first time each logger get() method is called. So, the loggers are not initialized before main(). However, static variable initialization is guaranteed to be thread safe, so perhaps there was a threading issue. 
Nonetheless, the crash is fixed with these changes.

**Comment by ethouris** [comment]
This change shall be provided the way that is transparent to the current code.

As an example, in one of my experimental branch (on my SRT repo replica), `dev-fag`, I've added a mechanism of doing global initialization of a map that is triggered effectively from the `srt_startup()` so that it doesn't use the global constructor, in the `smoother.h` file. This initializes the global map with builtin smoothers so that new smoothers can be added through a method.

A similar global initialization should be done also for the logging system.

Another possibility is that the objects that are themselves initialized should be made static, just the level-bound executors should be moved to another object, which is bound to this one by address at the constructor time (even though the object is only about to be constructed), and then refer to it when called (while the call will happen already after construction).

**Comment by boxerab** [comment]
Thanks @ethouris . This refactor sounds like a good idea. In the mean time, this PR makes minimal changes to the code, it follows the Meyers singleton pattern for creating singleton logger objects, and it fixes the crash issue. Perhaps we can merge this for now, and do the refactor in another PR ?

**Comment by boxerab** [comment]
Since this crash has been fixed by @ethouris on another branch, I will close this PR.

**Pull request closed without merging**
