### PR TITLE
MingW build fixes

### PR DESCRIPTION
**Pull request by ocrete**
I had a bunch of little issues with the MingW cross compile of SRT 1.3.0 to integrate it into the GStreamer CI.

Please review these changes super carefully and maybe try to build them in your environments. Maybe SRT's CI should also add builds for other platforms like Android & MingW as it's quite painful to make sure none of those get broken without such a tool.

### CODE REVIEW

**Comment by rodebiet** [comment]
I still have errors cross compiling your branch:

[ 29%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/epoll.cpp.o
/tmp/workdir/srt/srtcore/epoll.cpp:54:13: fatal error: sys/epoll.h: No such file or directory
    #include <sys/epoll.h>
             ^~~~~~~~~~~~~
[ 53%] Building CXX object CMakeFiles/srtsupport_virtual.dir/apps/logsupport.cpp.o
In file included from /tmp/workdir/srt/apps/../srtcore/srt.h:21:0,
                 from /tmp/workdir/srt/apps/logsupport.hpp:14,
                 from /tmp/workdir/srt/apps/logsupport.cpp:16:
/tmp/workdir/srt/apps/../srtcore/platform_sys.h:25:10: fatal error: sys/socket.h: No such file or directory
 #include <sys/socket.h>
          ^~~~~~~~~~~~~~

My docker setup is:
RUN git clone --recursive -b mingw https://github.com/ocrete/srt.git

RUN cd srt && ./configure --with-compiler-prefix=x86_64-w64-mingw32- --openssl-crypto-library=../openssl/libcrypto.a --openssl-ssl-library=../openssl/libssl.a --openssl-include-dir=../openssl/include/ --pthread-include-dir=../pthreads/x86_64-w64-mingw32/include/ --pthread-library=../pthreads/x86_64-w64-mingw32/lib/libpthread.a

**Comment by ethouris** [comment]
How is this possible that a MinGW compiler gets this line:
```
#ifdef LINUX
   #include <sys/epoll.h>
   #include <unistd.h>
#endif
```
The result from clean running cmake would help here.

**Comment by rndi** [comment]
Is this PR still needed now that #426 is merged in?

**Comment by ocrete** [comment]
I don't think this is needed anymore. Lets close those.

**Comment by rodebiet** [comment]
After merge #426 still
[ 47%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/epoll.cpp.o
/tmp/workdir/srt/srtcore/epoll.cpp:54:13: fatal error: sys/epoll.h: No such file or directory
    #include <sys/epoll.h>
             ^~~~~~~~~~~~~

**Comment by rodebiet** [comment]
cmake . -DWITH_COMPILER_PREFIX=x86_64-w64-mingw32- -DOPENSSL_CRYPTO_LIBRARY=../openssl/libcrypto.a -DOPENSSL_SSL_LIBRARY=../openssl/libssl.a -DOPENSSL_INCLUDE_DIR=../openssl/include/ -DPTHREAD_INCLUDE_DIR=../pthreads/x86_64-w64-mingw32/include/ -DPTHREAD_LIBRARY=../pthreads/x86_64-w64-mingw32/lib/libpthread.a
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- BUILD TYPE: Release
-- LOGGING: ENABLED
-- Handling compiler with WITH_COMPILER_PREFIX=x86_64-w64-mingw32-
-- Found OpenSSL: /tmp/workdir/openssl/libcrypto.a (found version "1.1.1") 
-- SSL Dependency: using OpenSSL (default)
-- SSL libraries: /tmp/workdir/openssl/libssl.a;/tmp/workdir/openssl/libcrypto.a
-- COMPILER: GNU compat: x86_64-w64-mingw32-g++
-- DETECTED SYSTEM: LINUX;  LINUX=1
-- Pthread library: ../pthreads/x86_64-w64-mingw32/lib/libpthread.a
-- Pthread include dir: ../pthreads/x86_64-w64-mingw32/include/
-- ADDING TRANSITIVE LINK DEP to:srt_shared : ../pthreads/x86_64-w64-mingw32/lib/libpthread.a 
-- ADDING TRANSITIVE LINK DEP to:srt_static : ../pthreads/x86_64-w64-mingw32/lib/libpthread.a 
-- INSTALL DIRS: bin=bin lib=lib shlib=lib include=include
-- C++ VERSION: Setting C++11 compat flag for gnu compiler
-- BACKWARD COMPATIBLE 'stransmit': will use symbolic link
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/workdir/srt

**Pull request closed without merging**
