### PR TITLE
Added Google Test framework

### PR DESCRIPTION
**Pull request by maxlovic**
Including the test from the issue #468

### CODE REVIEW

**Comment by gegles** [comment]
Ah!!! Why Google Test! [Catch2](https://github.com/catchorg/Catch2) is so much better, easier, more modern... Thanks for the work, though.

If there is any chance you can still switch to Catch2, I think it would greatly be appreciated by all.

**Comment by alexpokotilo** [comment]
> We are trying to keep the source C++03 max, at least for the main lib. The reasoning for this is probably out of scope for this comment section and may change with time

I understand that library internals not related to library API but let me give some thoughts on the subject in anyway.
Please always keep C API for SRT library as well as library C++ version on 03 level. It's still important for mobiles|embedded and old linux systems without native Modern C++ support. I love Modern C++ but code quality depends on how deeply you get new features and language rules. It's ok to use it in utilities as you do but there are still a lot of great C++ programmers without Modern C++ experience and we can decrease library community a lot. I don't think it's a big problem to use Modern C++ in UTs but if we can used library C API with old google test we can do that as well.

**Comment by gegles** [comment]
I can't speak to Catch1, I've never used it. I also get that you may have good reasons to stick with C++03.

That being said,  couldn't we simply keep the libraries/apps (i.e. the distributables) to C++03 but enable C++11 for the UTs?

With CMake you can easily enforce theses things on a per-target or per-directory basis (using [CXX_STANDARD](https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html#prop_tgt:CXX_STANDARD) property).

My 2 cents.

**Comment by maxlovic** [comment]
**Catch2** lacks the mocking functionality. I do not see an easy way to integrate mock objects with the current SRT code base. But I think we should look into this to mock at least network objects and improve stability through unit tests. With **Catch2** we would have to bring in an additional library like **FakeIt**. Not a big deal, though. What **Catch2** does have, is BDD testing. That is a strong advantage, in my opinion.
I was looking into **GUnit** as a potential improvement over **Google Tests** though.
I would say that for now, it is more about having the tests themselves, rather than the framework to use. Switching to another testing framework over time is not a big deal unless we stick really deep to the certain framework's features like mocking, or maybe BDD. At least on the code level, it is not a blocker. It might be a notable deal for the community though.
What do you, guys, think? My suggestion is to stick to **Google Tests** for now unless you disagree with my statements.

**Comment by alexpokotilo** [comment]
+1 for Google Tests

**Pull request merged**
