### PR TITLE
A crypto service provider based on Botan

### PR DESCRIPTION
**Pull request by oviano**
As my project primarily uses Botan (https://botan.randombit.net) I decided to write a Botan cryspr for SRT so that I could drop my dependency on multiple crypto libs.

I'm sharing this in case it is of interest to anyone. I've not integrated this into the SRT build system(s) at this stage as I do not use them; instead dropping the SRT files directly into my projects.

### CODE REVIEW

**Comment by oviano** [comment]
So, it's a work in progress at the moment - I've only just realised Botan has a C API wrapper so I'm changing it to use that in any case, then I don't need to have the botan_sys workaround for the C++/C problem and it makes things cleaner.

I started by looking at MBedTLS, then realised that ECB wasn't supported by Botan, but it has AES keywrap functions so I enabled that option.

I will look a AES-GCM - I expect Botan does support that, so I'll have a look at the openssl-eve wrapper....

More to come later anyway.

**Comment by maxsharabayko** [comment]
Thnk you for the proposal, @oviano!
Please also consider extending the CMake build option `USE_ENCLIB=botan`.

**Comment by oviano** [comment]
A quick Q as I figure this out:

None of the existing crysprs set the km_setkey callback. This means that when it needs to set the key it relies on the fallback callback:

```
static int crysprFallback_KmSetKey(CRYSPR_cb *cryspr_cb, bool bWrap, const unsigned char *kek, size_t kek_len)
{
	CRYSPR_AESCTX *aes_kek = CRYSPR_GETKEK(cryspr_cb);

	if (cryspr_cb->cryspr->aes_set_key(HCRYPT_CTX_MODE_AESECB, bWrap, kek, kek_len, aes_kek)) {
		HCRYPT_LOG(LOG_ERR, "aes_set_%s_key(kek) failed\n", bWrap? "encrypt": "decrypt");
		return(-1);
	}
	return(0);
}
```

Thus, it will pass HCRYPT_CTX_MODE_AESECB into the aes_set_key callback for the kek.

In the case of openssl_evp, since this cryspr supports ECB, it just configures the key for ECB.

However, others, such as MBedTLS just always use CTR regardless of what is passed in (it ignores the cipher_type).

In the case of Botan, I do not have ECB, but I could use either CTR or GSM. But in any case shouldn't it choose the same algo as for the SEK keys, as I am building with ENABLE_AEAD_API_PREVIEW and thus it is selectable.

However, I don't see how the code allows for that, as the fallback callback above always passes HCRYPT_CTX_MODE_AESECB?

Am I missing anything - should the ENABLE_AEAD_API_PREVIEW also allow configuring the KEK cipher type swell as the SEK cipher type, or is it only intended to control the SEK and I can use whatever I want for the KEK?

**Comment by randombit** [comment]
@oviano Just a FYI - AES-GCM is certainly supported. Also ECB *is* available, both via the C and C++ APIs, but only via the raw block cipher interface. Eg in the C API `botan_block_cipher_encrypt_blocks` == ECB encryption.

**Comment by oviano** [comment]
> @oviano Just a FYI - AES-GCM is certainly supported. Also ECB _is_ available, both via the C and C++ APIs, but only via the raw block cipher interface. Eg in the C API `botan_block_cipher_encrypt_blocks` == ECB encryption.

Great thanks for the info. I’ve just committed AES-GCM support actually. ECB seems like a fallback option for when CTR or GCM is not available in the cryptolib so doesn’t seem much point in adding.

**Comment by oviano** [comment]
So it now works with both AES-CTR and AES-GCM, and the only thing it needs is someone to finish off what is required in CMakeLists.txt to allow it to find the Botan install and link to the relevant libraries etc.

I don't have enough experience with CMake for this to be something trivial for me.

**Comment by oviano** [comment]
I've taken this as far as I can now, I think.

The cryspr itself works fine, and builds on my macOS machine as below.

It likely needs some work/testing on other platforms though, which I can't help with.

```
oliver@Ovs-MacBook-Pro srt % ./configure --use-enclib=botan --enable-stdc++-sync --enable-aead-api-preview --disable-apps
NOTE: --disable-apps changed into --enable-apps=0
Running: cmake . -DUSE_ENCLIB=botan -DENABLE_STDCXX_SYNC=1 -DENABLE_AEAD_API_PREVIEW=1 -DENABLE_APPS=0
-- The C compiler identification is AppleClang 14.0.3.14030022
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- BUILD TYPE: Release
-- Performing Test HAVE_CLOCK_GETTIME_IN
-- Performing Test HAVE_CLOCK_GETTIME_IN - Success
-- CLOCK_MONOTONIC: available, no extra libs needed
-- LOGGING: ENABLED
-- USE_BUSY_WAITING: OFF (default)
-- No WITH_COMPILER_PREFIX - using C++ compiler /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Looking for inet_pton
-- Looking for inet_pton - found
-- Checking for pthread_(g/s)etname_np in 'pthread_np.h':
-- Looking for pthread_getname_np
-- Looking for pthread_getname_np - not found
-- Looking for pthread_setname_np
-- Looking for pthread_setname_np - not found
-- Checking for pthread_(g/s)etname_np in 'pthread.h':
-- Looking for pthread_getname_np
-- Looking for pthread_getname_np - found
-- Looking for pthread_setname_np
-- Looking for pthread_setname_np - found
-- Found Python: /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/bin/python3.9 (found version "3.9.6") found components: Interpreter 
-- ENCRYPTION: ENABLED, using: botan
-- SSL libraries: botan
-- ENCRYPTION AEAD API: ENABLED
-- COMPILER: Clang (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++) - GNU compat
-- NOTE: CLANG 14.0.3.14030022 detected, unsure if >=C++11 is default, forcing C++11 on applications
-- Looking for __atomic_fetch_add_8 in atomic
-- Looking for __atomic_fetch_add_8 in atomic - not found
-- Performing Test HAVE_LIBATOMIC_COMPILES
-- Performing Test HAVE_LIBATOMIC_COMPILES - Failed
-- Performing Test HAVE_GCCATOMIC_INTRINSICS
-- Performing Test HAVE_GCCATOMIC_INTRINSICS - Success
-- Performing Test HAVE_CXX_ATOMIC
-- Performing Test HAVE_CXX_ATOMIC - Success
-- Performing Test HAVE_CXX_ATOMIC_STATIC
-- Performing Test HAVE_CXX_ATOMIC_STATIC - Failed
-- Checking for C++ 'std::put_time()':
-- Performing Test HAVE_CXX_STD_PUT_TIME
-- Performing Test HAVE_CXX_STD_PUT_TIME - Success
-- STDCXX_SYNC: 1
-- MONOTONIC_CLOCK: ON
-- C++ STANDARD: using C++11 for all
-- C++: Setting C++ standard for gnu compiler: lib:  apps: 
-- DETECTED SYSTEM: DARWIN
-- ENABLE_BONDING: OFF
-- Pthread library: C++11
-- APP: srt_virtual: using default C++ standard
-- ADDING TRANSITIVE LINK DEP to:srt_shared :  
-- ADDING TRANSITIVE LINK DEP to:srt_static :  
-- INSTALL DIRS: bin=bin lib=lib shlib=lib include=include
-- APPS: DISABLED
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/oliver/git/source/thirdparty/srt
oliver@Ovs-MacBook-Pro srt % make
[  2%] Generating Botan amalgamation files botan_all.cpp and botan_all.h
   INFO: /Users/oliver/git/source/thirdparty/srt/_deps/botan_upstream-src/configure.py invoked with options "--cc-bin=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ --cc=clang --disable-shared --amalgamation --with-build-dir=botan --minimized-build --enable-modules=ffi,nist_keywrap,aes_armv8,aes_ni,aes_power8,aes_vperm,idea_sse2,serpent_avx2,shacal2_armv8,shacal2_avx2,shacal2_x86,sm4_armv8,rdseed,sha1_armv8,sha1_sse2,sha1_x86,sha2_32_armv8,sha2_32_bmi2,sha2_32_x86,sha2_64_bmi2,sha3_bmi2,zfec_sse2,zfec_vperm,argon2_avx2,argon2_ssse3,processor_rng,chacha_avx2,ghash_cpu,ghash_vperm,simd,simd_avx2"
   INFO: Configuring to build Botan 3.0.0-rc1 (revision git:17fa4a6126d298f70a39972a4b50a66757ad9b94)
   INFO: Running under 3.9.6 (default, Mar 10 2023, 20:16:38) [Clang 14.0.3 (clang-1403.0.22.14.1)]
   INFO: Autodetected platform information: OS="Darwin" machine="arm64" proc="arm"
   INFO: Guessing target OS is darwin (use --os to set)
   INFO: Guessing target processor is a arm64 (use --cpu to set)
   INFO: Using /etc/ssl/cert.pem as system certificate store
   INFO: Auto-detected compiler version 14.0
   INFO: Auto-detected compiler arch arm64
   INFO: Target is clang:14.0-macos-arm64
   INFO: Assuming target arm64 is little endian
   INFO: Skipping (incompatible CPU): aes_ni aes_power8 argon2_avx2 argon2_ssse3 chacha_avx2 ghash_vperm idea_sse2 processor_rng rdseed serpent_avx2 sha1_sse2 sha1_x86 sha2_32_bmi2 sha2_32_x86 sha2_64_bmi2 sha3_bmi2 shacal2_avx2 shacal2_x86 simd_avx2 zfec_sse2
   INFO: Skipping (incompatible OS): certstor_system_windows win32_stats
   INFO: Skipping (incompatible compiler): sm4_armv8
   INFO: Skipping (not requested): adler32 argon2 argon2fmt aria asio base32 base58 bcrypt bcrypt_pbkdf blake2 blake2mac blowfish camellia cascade cast128 cbc ccm certstor_flatfile certstor_sql certstor_sqlite3 certstor_system certstor_system_macos cfb chacha chacha20poly1305 chacha_rng chacha_simd32 checksum cmac comb4p compression crc24 crc32 cryptobox ctr curve25519 des dh dilithium dilithium_aes dilithium_common dl_algo dl_group dlies dsa dyn_load eax ec_group ec_h2c ecc_key ecdh ecdsa ecgdsa ecies eckcdsa ed25519 elgamal eme_oaep eme_pkcs1 eme_raw emsa_pkcs1 emsa_pssr emsa_raw emsa_x931 fd_unix filters fpe_fe1 gcm getentropy gmac gost_28147 gost_3410 gost_3411 hash_id hkdf hotp http_util idea iso9796 kdf1 kdf1_iso18033 kdf2 keccak keypair kyber kyber_90s kyber_common lion locking_allocator mce md4 md5 mem_pool mgf1 mode_pad noekeon noekeon_simd ocb ofb par_hash passhash9 pbes2 pbkdf2 pgp_s2k pkcs11 poly1305 poly_dbl prf_tls prf_x942 psk_db raw_hash rc4 rfc3394 rfc6979 rmd160 roughtime rsa salsa20 scrypt seed serpent serpent_simd sessions_sql sessions_sqlite3 sha2_64 sha3 shacal2_simd shake shake_cipher siphash siv skein sm2 sm3 sm4 socket sodium sp800_108 sp800_56a sp800_56c srp6 streebog thread_utils threefish_512 tls tls12 tls13 tls_cbc trunc_hash tss twofish uuid whirlpool x509 x919_mac xmss xts
   INFO: Skipping (requires external dependency): boost bzip2 commoncrypto lzma sqlite3 tpm zlib
   INFO: Loading modules: aead aes aes_armv8 aes_vperm asn1 auto_rng base base64 bigint block cpuid entropy ffi ghash ghash_cpu hash hex hmac hmac_drbg kdf mac mdx_hash modes mp nist_keywrap numbertheory pbkdf pem pk_pad pubkey rng sha1 sha1_armv8 sha2_32 sha2_32_armv8 shacal2 shacal2_armv8 simd stateful_rng stream system_rng utils zfec zfec_vperm
   INFO: Using symlink to link files into build dir (use --link-method to change)
   INFO: Writing amalgamation header to botan_all.h
   INFO: Writing amalgamation source to botan_all.cpp
   INFO: Botan 3.0.0-rc1 (revision git:17fa4a6126d298f70a39972a4b50a66757ad9b94) (unreleased undated) build setup is complete
Consolidate compiler generated dependencies of target botan
[  4%] Building CXX object CMakeFiles/botan.dir/botan_all.cpp.o
/Users/oliver/git/source/thirdparty/srt/botan_all.cpp:32256:42: warning: unused parameter 'key_bits' [-Wunused-parameter]
                std::span<const uint8_t> key_bits)
                                         ^
/Users/oliver/git/source/thirdparty/srt/botan_all.cpp:32347:43: warning: unused parameter 'key_bits' [-Wunused-parameter]
                 std::span<const uint8_t> key_bits)
                                          ^
'++crypto' is not a recognized feature for this target (ignoring feature)
'++crypto' is not a recognized feature for this target (ignoring feature)
'++simd' is not a recognized feature for this target (ignoring feature)
'++simd' is not a recognized feature for this target (ignoring feature)
2 warnings generated.
[  6%] Linking CXX static library libbotan.a
Copying build.h file
Copying compiler.h file
Copying ffi.h file
[  6%] Built target botan
Consolidate compiler generated dependencies of target srt_virtual
[  8%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/api.cpp.o
[ 10%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/buffer_snd.cpp.o
[ 12%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/buffer_rcv.cpp.o
[ 14%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/buffer_tools.cpp.o
[ 17%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/cache.cpp.o
[ 19%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/channel.cpp.o
[ 21%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/common.cpp.o
[ 23%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/core.cpp.o
[ 25%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/crypto.cpp.o
[ 27%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/epoll.cpp.o
[ 29%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/fec.cpp.o
[ 31%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/handshake.cpp.o
[ 34%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/list.cpp.o
[ 36%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/logger_default.cpp.o
[ 38%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/logger_defs.cpp.o
[ 40%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/md5.cpp.o
[ 42%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/packet.cpp.o
[ 44%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/packetfilter.cpp.o
[ 46%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/queue.cpp.o
[ 48%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/congctl.cpp.o
[ 51%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/socketconfig.cpp.o
[ 53%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/srt_c_api.cpp.o
[ 55%] Building C object CMakeFiles/srt_virtual.dir/srtcore/srt_compat.c.o
[ 57%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/strerror_defs.cpp.o
[ 59%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/sync.cpp.o
[ 61%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/tsbpd_time.cpp.o
[ 63%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/window.cpp.o
[ 65%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/sync_cxx11.cpp.o
[ 68%] Building C object CMakeFiles/srt_virtual.dir/haicrypt/cryspr.c.o
[ 70%] Building C object CMakeFiles/srt_virtual.dir/haicrypt/cryspr-botan.c.o
[ 72%] Building C object CMakeFiles/srt_virtual.dir/haicrypt/hcrypt.c.o
[ 74%] Building C object CMakeFiles/srt_virtual.dir/haicrypt/hcrypt_ctx_rx.c.o
[ 76%] Building C object CMakeFiles/srt_virtual.dir/haicrypt/hcrypt_ctx_tx.c.o
[ 78%] Building C object CMakeFiles/srt_virtual.dir/haicrypt/hcrypt_rx.c.o
[ 80%] Building C object CMakeFiles/srt_virtual.dir/haicrypt/hcrypt_sa.c.o
[ 82%] Building C object CMakeFiles/srt_virtual.dir/haicrypt/hcrypt_tx.c.o
[ 85%] Building C object CMakeFiles/srt_virtual.dir/haicrypt/hcrypt_xpt_srt.c.o
[ 87%] Building CXX object CMakeFiles/srt_virtual.dir/haicrypt/haicrypt_log.cpp.o
[ 87%] Built target srt_virtual
Consolidate compiler generated dependencies of target srt_shared
[ 89%] Building C object CMakeFiles/srt_shared.dir/cmake_object_lib_support.c.o
[ 91%] Linking CXX shared library libsrt.dylib
[ 93%] Built target srt_shared
Consolidate compiler generated dependencies of target srt_static
[ 95%] Building C object CMakeFiles/srt_static.dir/cmake_object_lib_support.c.o
[ 97%] Linking CXX static library libsrt.a
[100%] Built target srt_static
```

**Comment by oviano** [comment]
I now have this building on Android, iOS and macOS. This was tested on a macOS host.

It works by directly cloning the Botan GitHub repo, configuring an amalgamated build, building a simple static library and linking to the SRT build. The only pre-requisites are that python3 must be found in the path so it can run the Botan configure script, and the new fields --botan-os and --botan-cpu must be passed in so that Botan can configure the appropriate intrinsic modules etc.

```
Android

./build-android -n /Users/Oliver/Library/Android/sdk/ndk/25.1.8937393 -e botan -t armeabi-v7a
./build-android -n /Users/Oliver/Library/Android/sdk/ndk/25.1.8937393 -e botan -t arm64-v8a
./build-android -n /Users/Oliver/Library/Android/sdk/ndk/25.1.8937393 -e botan -t x86
./build-android -n /Users/Oliver/Library/Android/sdk/ndk/25.1.8937393 -e botan -t x86_64

iOS

./configure --cmake-toolchain-file=scripts/iOS.cmake --ios-arch=arm64 --use-enclib=botan --botan-os=ios --botan-cpu=arm64
./configure --cmake-toolchain-file=scripts/iOS.cmake --ios-arch=armv7 --use-enclib=botan --botan-os=ios --botan-cpu=armv7

macOS

./configure --CMAKE_OSX_ARCHITECTURES=arm64 --use-enclib=botan --botan-os=macos --botan-cpu=arm64
./configure --CMAKE_OSX_ARCHITECTURES=x86_64 --use-enclib=botan --botan-os=macos --botan-cpu=x86_64
```

**Comment by oviano** [comment]
```
Windows

cmake . -G"Visual Studio 17 2022" -A x64 -DUSE_ENCLIB=botan -DBOTAN_OS=windows -DBOTAN_CPU=x86_64
cmake --build .
```

**Comment by oviano** [comment]
Linux

```
./configure --use-enclib=botan --botan-os=linux --botan-cpu=x86_64
make
```

**Comment by oviano** [comment]
> Thnk you for the proposal, @oviano!
> Please also consider extending the CMake build option `USE_ENCLIB=botan`.

I've now integrated this into the CMake system and I have built it on Android (macOS host), macOS, iOS, Windows and Linux (Ubuntu 22.04 VM).

Here is a summary of the build commands necessary:

```
Android (armv7a, armv8a, x86, x86_64)

./build-android -n /Users/Oliver/Library/Android/sdk/ndk/25.1.8937393 -e botan -t armeabi-v7a
./build-android -n /Users/Oliver/Library/Android/sdk/ndk/25.1.8937393 -e botan -t arm64-v8a
./build-android -n /Users/Oliver/Library/Android/sdk/ndk/25.1.8937393 -e botan -t x86
./build-android -n /Users/Oliver/Library/Android/sdk/ndk/25.1.8937393 -e botan -t x86_64

iOS (arm64, armv7)

./configure --cmake-toolchain-file=scripts/iOS.cmake --ios-arch=arm64 --use-enclib=botan --botan-os=ios --botan-cpu=arm64
make
./configure --cmake-toolchain-file=scripts/iOS.cmake --ios-arch=armv7 --use-enclib=botan --botan-os=ios --botan-cpu=armv7
make

macOS (arm64, x86_64)

./configure --CMAKE_OSX_ARCHITECTURES=arm64 --use-enclib=botan --botan-os=macos --botan-cpu=arm64
make
./configure --CMAKE_OSX_ARCHITECTURES=x86_64 --use-enclib=botan --botan-os=macos --botan-cpu=x86_64
make

Windows (x86_64)

cmake . -G"Visual Studio 17 2022" -A x64 -DUSE_ENCLIB=botan -DBOTAN_OS=windows -DBOTAN_CPU=x86_64
cmake --build .

Linux (x86_64)

./configure --use-enclib=botan --botan-os=linux --botan-cpu=x86_64
make
```

Specifying the enclib as botan triggers FindBotan.cmake to be used (this is in the scripts folder), which checks the botan source out from GitHub, creates the amalgamation files and builds a simple static library which is linked to srt.

It's all automatic, except for having to pass in botan-os and botan-cpu as shown above to tell Botan to configure the amalgamation files correctly (including the required intrinsics, for example).

**Pull request merged**
